.travis.yml
Let's see if this works in this repo!
=> Add Travis Buddy

compose/.apps/muximux/muximux.yml
Hopefully travis uses the correct PR build for the checks on this.
=> Use correct image for Muximux

compose/generate-yml.sh
Builds in my test PR https://github.com/GhostWriters/DockSTARTer/pull/31 from this branch to the generator test branch were successful, so this change should work fine together with the generator test and both this PR as well as https://github.com/GhostWriters/DockSTARTer/pull/30 can merge.
=> Prompt whether to run containers after generation.

.gitignore
Per conversation about https://docs.docker.com/compose/extends/
=> Ignore default docker-compose.override.yml

main.sh, scripts/enable_docker_systemd.sh, scripts/generate_yml.sh, scripts/get_env.sh, scripts/install_compose.sh, scripts/install_compose_completion.sh, scripts/install_docker.sh, scripts/install_machine_completion.sh, scripts/install_yq.sh, scripts/request_reboot.sh, scripts/root_check.sh, scripts/run_apt.sh, scripts/run_compose.sh, scripts/setup_docker_group.sh, test/run_generate.sh, test/validate_newline.sh, test/validate_shellcheck.sh
https://google.github.io/styleguide/shell.xml
This is actually ready now.
=> Cleanup various inconsistencies

compose/.apps/watchtower/watchtower.ports.yml
This solves the warning in #57
=> Add dummy ports file for watchtower

main.sh, scripts/generate_yml.sh, scripts/request_reboot.sh, scripts/root_check.sh, scripts/run_compose.sh, scripts/update_self.sh, tests/validate_shellcheck.sh
This is a good start. Next I'll actually start having the script do some legit logging so we can request that users send us their log and it actually make sense.
=> Add logging functions

main.sh, scripts/cmd_install.sh, scripts/cmd_update.sh, scripts/install_compose.sh, scripts/install_docker.sh, scripts/install_yq.sh, scripts/run_apt.sh
This handles a lot better than what I had for updates. It also allows forcing updates. Also takes care of compose on arm with pip for #74
=> Fixup installer functions and update checks

.travis.yml, main.sh, scripts/enable_docker_systemd.sh, scripts/generate_yml.sh, scripts/install_compose.sh, scripts/install_compose_completion.sh, scripts/install_docker.sh, scripts/install_machine_completion.sh, scripts/install_yq.sh, scripts/request_reboot.sh, scripts/root_check.sh, scripts/run_apt.sh, scripts/run_compose.sh, scripts/setup_docker_group.sh, scripts/update_self.sh, tests/run_generate.sh, tests/run_install.sh, tests/validate_bashate.sh, tests/validate_newline.sh, tests/validate_shellcheck.sh
This ended up working out pretty nice to cleanup the output.
Here is what I get running the installer:
```
baines@yori:~/.docker$ sudo bash main.sh -i
[INFO]        Checking root permissions.
[INFO]        Updating repositories.
[INFO]        Upgrading packages.
[INFO]        Installing dependencies.
[INFO]        Removing unused packages.
[INFO]        Cleaning up unused packages.
[INFO]        Installing latest yq.
[INFO]        Installing latest docker. Please be patient, this will take a while.
[INFO]        Installing docker machine completion.
[INFO]        Installing latest compose.
[INFO]        Installing docker compose completion.
[INFO]        Creating docker group.
[INFO]        Adding root to docker group.
[INFO]        Systemd detected. Enabling docker service.
[INFO] …
```
=> Make more use of logging.

scripts/install_compose.sh
https://github.com/docker/compose/issues/4874
Two things here
1. `docker-py` is apparently an issue (so, remove it!)
2. the `-U` flag should tell this section to update compose if it's already installed.
=> Apply another fix for installing compose on arm

scripts/install_compose.sh, scripts/install_docker.sh, scripts/install_yq.sh
This was accidentally setting the installed version to blank and making the script install/reinstall these every time the generator runs. This is now properly tested and working as expected.
=> Fix version checks

scripts/request_reboot.sh, scripts/run_compose.sh, scripts/update_self.sh
To trigger any of these to use the GUI we change
```
run_script 'request_reboot'
```
to
```
run_script 'request_reboot' menu
```
=> Adjust yes/no prompts to prepare for menus

scripts/menus/config_folder_set.sh, scripts/menus/download_folder_set.sh, scripts/menus/media_folders_set.sh, scripts/menus/timezone_set.sh
Detects if the .env file has a parameter set.
If blank then defaults to suggested.
=> Media check

scripts/cmdline.sh, scripts/menus/menu_main.sh, scripts/prune_docker.sh
This is nice and clean and is the recommended way from docker to do a full cleanup of all unused docker resources per their documentation https://docs.docker.com/config/pruning/#prune-everything
This also resolves https://feathub.com/GhostWriters/DockSTARTer/+14
=> Add prune option

main.sh
This should have been in the prune PR but I forgot to add it.
=> Add usage info for prune cmd flag

scripts/menu_app_select.sh
=> Deselect all apps before enabling apps via the GUI

compose/.apps/bazarr/bazarr.arm64.yml, compose/.apps/bazarr/bazarr.armhf.yml
I'll update the wiki once this is merged.
Closes #132
=> Added Bazarr arm64 and armhf images

.gitignore, scripts/cmdline.sh, scripts/env_backup.sh, scripts/menu_main.sh
=> Add option to backup .env

.github/CONTRIBUTING.md
_Describe the problem or feature in addition to a link to the issues._
_How does this change address the problem?_
_Describe the research stage_
_Links to blog posts, patterns, libraries or addons used to solve this problem_
=> Contributing

README.md
Begin addressing #147 Show screenshots and include basic information
Add info and screenshots to the readme so they are presented up front and more easily accessible.
Review will be requested when the PR is actually ready.
=> New badges and Getting Started for README

compose/.apps/netdata/netdata.yml
Fix netdata spamming journal with apparmor messages.
Add the proper fix to the yml.
https://github.com/titpetric/netdata/issues/55
=> Fix netdata journal apparmor

scripts/env_update.sh, scripts/menu_value_prompt.sh
This should be the last of the grep fixes.
=> More grep fixes

compose/.apps/netdata/netdata.arm64.yml, compose/.apps/netdata/netdata.armhf.yml, compose/.apps/netdata/netdata.yml
Netdata has moved their images (again). Use the new images.
Update the files.
=> Use new netdata images

compose/.apps/airsonic/airsonic.arm64.yml, compose/.apps/airsonic/airsonic.armhf.yml, compose/.apps/glances/glances.yml, compose/.apps/homeassistant/homeassistant.arm64.yml, compose/.apps/homeassistant/homeassistant.armhf.yml, compose/.apps/plex/plex.yml, compose/.apps/ubooquity/ubooquity.arm64.yml, compose/.apps/ubooquity/ubooquity.armhf.yml
Keep files pretty
Run each YML file through Atom Beautify
=> Fix indentation

main.sh
Add a comment to the site that describes all the colors so we don't have to google it in the future
See above
https://misc.flogisoft.com/bash/tip_colors_and_formatting
=> Add comment for colors

README.md
=> New URL for readme

scripts/env_backup.sh, scripts/env_update.sh
Fix new backup removal error and change some errors to warnings.
=> Change some errors to warnings

main.sh, scripts/enable_docker_systemd.sh, scripts/env_set.sh, scripts/generate_yml.sh, scripts/install_compose.sh, scripts/install_compose_completion.sh, scripts/install_docker.sh, scripts/install_machine_completion.sh, scripts/install_yq.sh, scripts/prune_docker.sh, scripts/request_reboot.sh, scripts/run_apt.sh, scripts/run_dnf.sh, scripts/run_yum.sh, scripts/symlink_ds.sh, scripts/update_self.sh, scripts/update_system.sh, tests/validate_bashate.sh, tests/validate_newline.sh, tests/validate_shellcheck.sh
Add failure logging to everything.
If it's failing it's already exiting the script anyway, may as well log what's happening.
=> Add failure logging to everything.

main.sh, scripts/cmdline.sh
Allow people to run with `-h` or `--help`
Add cmdline option and usage information
=> Add -h and --help flags to show usage

scripts/env_create.sh, scripts/prune_docker.sh, scripts/request_reboot.sh, scripts/run_compose.sh, scripts/update_self.sh
=> Remove whitespace from Yn cases

main.sh
Add usage information about backups
=> Add backup information to usage

main.sh, scripts/backup_create.sh, scripts/backup_max.sh, scripts/backup_med.sh, scripts/backup_min.sh, scripts/env_set.sh, scripts/generate_yml.sh, scripts/prune_docker.sh, scripts/run_compose.sh, scripts/setup_docker_group.sh, scripts/symlink_ds.sh, tests/run_generate_slim.sh, tests/run_install.sh
Handle situations where the `ds` symlink is setup incorrectly to the wrong location.
Check the location for the `ds` symlink against `${SCRIPTPATH}` and replace it if it's incorrect.
=> Add check to verify correct ds symlink location

scripts/env_update.sh
Improve handling of `env_update` and reduce potential mix-ups with incorrectly selecting the `NEWEST_ENV`
- Discontinue the use of `NEWEST_ENV`
- Copy the current `.env` file to a `mktemp` file for the purpose of updating
- Run the previously existing commands/functions to remove the existing `.env`, replace it with a copy of the newest `.env.example`, and then merge the previous `.env` values into the new file but use the `mktemp` file instead of `NEWEST_ENV`
=> Use mktemp for env_update

scripts/backup_max.sh, scripts/backup_med.sh, scripts/backup_min.sh, scripts/config_apps.sh, scripts/config_globals.sh, scripts/config_vpn.sh, tests/run_generate_slim.sh, tests/run_install.sh, tests/validate_bashate.sh, tests/validate_newline.sh, tests/validate_shellcheck.sh
Add additional logging to various functions to give more indications of what is happening.
=> Add various logging messages.

.github/CODE_OF_CONDUCT.md, .github/CONTRIBUTING.md, .github/ISSUE_TEMPLATE/bug_report.md, .github/PULL_REQUEST_TEMPLATE.md, .scripts/backup_create.sh, .scripts/cmdline.sh, .scripts/config_globals.sh, .scripts/config_vpn.sh, .scripts/generate_yml.sh, .scripts/install_compose.sh, .scripts/install_docker.sh, .scripts/install_yq.sh, .scripts/menu_app_select.sh, .scripts/menu_app_vars.sh, .scripts/menu_value_prompt.sh, .scripts/prune_docker.sh, .scripts/request_reboot.sh, .scripts/run_compose.sh, .scripts/run_dnf.sh, .scripts/run_yum.sh, .scripts/set_permissions.sh, .scripts/update_self.sh, main.sh
Use shfmt to clean up all shell code and make it more uniform.
Installed shfmt and ran it on all files.
https://github.com/mvdan/sh
=> Use shfmt on all shell scripts

.scripts/backup_create.sh, .scripts/menu_value_prompt.sh, .scripts/run_dnf.sh, .scripts/run_yum.sh, .tests/validate_shfmt.sh, .travis.yml
Add validation check for shfmt.
Create the tried l required files and update a few scripts to be compliant. The installation process could be improved in the future as it currently has issues using the GH header VAR for some reason.
https://github.com/mvdan/sh
=> Add shfmt validation

main.sh
Add additional comments showing where ideas and inspiration came from. Shorten `ENDCOLOR` to `NC`. Relocate `ARGS` as high as possible in the script without lowering usage info.
https://stackoverflow.com/a/246128/1384186
=> Comments and minor tweaks

.tests/validate_bashate.sh, .tests/validate_shellcheck.sh, .tests/validate_shfmt.sh, main.sh
Simplify validations further by using docker images.
https://hub.docker.com/r/textclean/bashate/
https://hub.docker.com/r/koalaman/shellcheck/
https://hub.docker.com/r/jamesmstone/shfmt/
=> Use docker containers for all validations

compose/.apps/pihole/pihole.arm64.yml, compose/.apps/pihole/pihole.armhf.yml, compose/.apps/pihole/pihole.yml
This closes #417 
Use multiarch image for pihole and add `dns` entries per their documentation's recommendation.
https://hub.docker.com/r/pihole/pihole/
=> Pihole dns

.scripts/cmdline.sh, .scripts/prune_docker.sh, .scripts/request_reboot.sh, .scripts/run_compose.sh, .scripts/update_self.sh, main.sh
Just some housekeeping.
Complete some todo items, ensure proper use of NC, and don't inline `&&` and `||` on the same line (use proper `if`).
=> Minor cleanup

.tests/run_generate_full.sh
See title.
Add an `info` to the full test script.
=> Log which app is being tested in full test.

.github/CONTRIBUTING.md
Fix the formatting in the contributing guidelines
Replace unnecessary dashes with whitespace
=> Format contributing guidelines with proper nested lists

compose/.apps/calibreweb/calibreweb.arm64.yml, compose/.apps/calibreweb/calibreweb.armhf.yml
Updated docker hub repo address to solve pull error highlighted in #436.
This might also be necessary for the aarch64 file but I do not have the hardware to test.
=> Added hyphen

.scripts/install_docker.sh
This closes #482 
Detect is `snap` exists on the system and then remove the docker package if it was installed by snap.
=> Remove snap Docker package

README.md
After further investigation I do not believe this project is a fit for Open Collective at this time. We may come back to it in the future if that fit changes.
Remove references to Open Collective and improve remaining readme elements.
=> Remove Open Collective

.scripts/cmdline.sh, .scripts/update_self.sh, main.sh
Make it easier to test new branches from the git repo. Clean up unused branches. Also make the usage info easier to read.
Reformat the usage info to use multiple lines. Add the ability to run `ds -u branch`. This will make future testing instructions look like this:
```bash
ds -u # regular update
ds -u origin/testing
```
Then the user can test whatever new stuff that branch adds.
https://stackoverflow.com/a/10610669/1384186
=> Git branches

.scripts/env_sanitize.sh, .scripts/env_set.sh, main.sh
Resolve breaking change. Keep the update functionality.
Move the functionality back to its original location to prevent issues during updates.
=> Adjust sed handling

compose/.apps/sonarr/sonarr.aarch64.yml, compose/.apps/sonarr/sonarr.armv7l.yml
https://hub.docker.com/r/linuxserver/sonarr
=> Switch sonarr to LSIO pipeline

compose/.apps/letsencrypt/letsencrypt.aarch64.yml, compose/.apps/letsencrypt/letsencrypt.armv7l.yml
https://hub.docker.com/r/linuxserver/letsencrypt
=> Switch letsencrypt to LSIO pipeline

compose/.apps/tautulli/tautulli.aarch64.yml, compose/.apps/tautulli/tautulli.armv7l.yml
https://hub.docker.com/r/linuxserver/tautulli
=> Switch tautulli to LSIO pipeline

compose/.apps/airsonic/airsonic.aarch64.yml, compose/.apps/airsonic/airsonic.armv7l.yml
https://hub.docker.com/r/linuxserver/airsonic
=> Switch airsonic to LSIO pipeline

compose/.apps/sickrage/sickrage.aarch64.yml, compose/.apps/sickrage/sickrage.armv7l.yml
https://hub.docker.com/r/linuxserver/sickrage
=> Switch sickrage to LSIO pipeline

compose/.apps/couchpotato/couchpotato.aarch64.yml, compose/.apps/couchpotato/couchpotato.armv7l.yml
https://hub.docker.com/r/linuxserver/couchpotato
=> Switch couchpotato to LSIO pipeline

compose/.apps/duplicati/duplicati.aarch64.yml, compose/.apps/duplicati/duplicati.armv7l.yml
https://hub.docker.com/r/linuxserver/duplicati
=> Switch duplicati to LSIO pipeline

compose/.apps/lidarr/lidarr.aarch64.yml, compose/.apps/lidarr/lidarr.armv7l.yml
https://hub.docker.com/r/linuxserver/lidarr
=> Switch lidarr to LSIO pipeline

compose/.apps/mylar/mylar.aarch64.yml, compose/.apps/mylar/mylar.armv7l.yml
https://hub.docker.com/r/linuxserver/mylar
=> Switch mylar to LSIO pipeline

compose/.apps/medusa/medusa.aarch64.yml, compose/.apps/medusa/medusa.armv7l.yml
https://hub.docker.com/r/linuxserver/medusa
=> Switch medusa to LSIO pipeline

compose/.apps/headphones/headphones.aarch64.yml, compose/.apps/headphones/headphones.armv7l.yml
https://hub.docker.com/r/linuxserver/headphones
=> Switch headphones to LSIO pipeline

compose/.apps/thelounge/thelounge.aarch64.yml, compose/.apps/thelounge/thelounge.armv7l.yml
https://hub.docker.com/r/linuxserver/thelounge
=> Switch thelounge to LSIO pipeline

compose/.apps/muximux/muximux.aarch64.yml, compose/.apps/muximux/muximux.armv7l.yml
https://hub.docker.com/r/linuxserver/muximux
=> Switch muximux to LSIO pipeline

compose/.apps/mariadb/mariadb.aarch64.yml, compose/.apps/mariadb/mariadb.armv7l.yml
https://hub.docker.com/r/linuxserver/mariadb
=> Switch mariadb to LSIO pipeline

compose/.apps/nextcloud/nextcloud.aarch64.yml, compose/.apps/nextcloud/nextcloud.armv7l.yml
https://hub.docker.com/r/linuxserver/nextcloud
https://github.com/linuxserver/docker-nextcloud
=> Switch nextcloud to LSIO pipeline

compose/.apps/unifi/unifi.aarch64.yml, compose/.apps/unifi/unifi.armv7l.yml, compose/.apps/unifi/unifi.x86_64.yml
https://hub.docker.com/r/linuxserver/unifi
https://github.com/linuxserver/docker-unifi
https://hub.docker.com/r/linuxserver/unifi-controller
https://github.com/linuxserver/docker-unifi-controller
https://blog.linuxserver.io/2019/02/18/changes-to-our-unifi-image/
=> Switch unifi to LSIO pipeline

README.md
https://markdownmonster.west-wind.com/docs/_4sf0may9m.htm
=> Attempt to fix formatting with GitHub Pages

.scripts/install_compose.sh
Silence the urllib segfault error message.
Add quiet flag to pip and adjust warnings to indicate that they are safe to ignore.
=> Quiet flag for pip

.scripts/env_get.sh, .scripts/env_set.sh, .scripts/menu_app_select.sh, .scripts/menu_value_prompt.sh, main.sh
Use `grep` with `\K` more often rather than piping to other things to do the work.
=> Use more efficient grep when possible

.scripts/env_set.sh, main.sh
Replace links that included my personal ID with proper links
Update get_scriptname with revisions from https://stackoverflow.com/posts/246128/revisions
=> StackOverflow updates

compose/.apps/plex/plex.yml
Reverts GhostWriters/DockSTARTer#570
=> Revert "Add host GPU into the Plex container for HW accelerated decoding"

.scripts/install_compose.sh, .scripts/install_compose_completion.sh, .scripts/install_docker.sh, .scripts/install_machine_completion.sh, .scripts/install_yq.sh
Attempt to allow failures caused by GitHub's rate limit.
Set available version to `0` if it can't be detected. If it is also not installed (installed version set to `0`) or we're running with force, then fatal. Otherwise warm and return (allowing to continue).
https://api.github.com/rate_limit
=> GitHub ratelimit

.scripts/run_yum.sh
Resolve the issues with our implantation of python3 on CentOS.
Install python3 from IUS using setup.ius.io (which also installs the epel repository).
https://setup.ius.io/
=> CentOS python3 fixes

main.sh
Cleanup some comments.
Adjust caps and wording
=> Cleanup comments

docs/bitwarden.md
Bitwarden document advising that container will install as root, however user can change to what ever user is required after install.
advising user how to chagne the permissions if required
_Describe the research stage_
_Links to blog posts, patterns, libraries or addons used to solve this problem_
=> bitwarden.md

docs/apps/plex.md
_Describe the problem or feature in addition to a link to the issues._
_How does this change address the problem?_
_Describe the research stage_
_Links to blog posts, patterns, libraries or addons used to solve this problem_
=> Updated to remove claim info

compose/.apps/bitwarden/bitwarden.aarch64.yml, compose/.apps/bitwarden/bitwarden.armv7l.yml, compose/.apps/bitwarden/bitwarden.x86_64.yml
Switch to new `bitwardenrs/server` image.
https://hub.docker.com/r/bitwardenrs/server
https://hub.docker.com/r/mprasil/bitwarden
https://github.com/dani-garcia/bitwarden_rs/wiki/starting-a-container
https://github.com/dani-garcia/bitwarden_rs/wiki/updating-the-bitwarden-image
=> Update to new bitwardenrs image

compose/.apps/unmanic/unmanic.hostname.yml, compose/.apps/unmanic/unmanic.labels.yml, compose/.apps/unmanic/unmanic.netmode.yml, compose/.apps/unmanic/unmanic.ports.yml, compose/.apps/unmanic/unmanic.x86_64.yml, compose/.apps/unmanic/unmanic.yml
This closes #503 
Add the required files
https://github.com/Josh5/unmanic
https://hub.docker.com/r/josh5/unmanic
=> Add Unmanic

.scripts/cmdline.sh, .travis.yml, main.sh
Fix new SC2034 issue.
Comment out the declaration of variables that are not being used.
https://github.com/koalaman/shellcheck/wiki/SC2034
https://github.com/nemchik/ShellSuite/pull/10
=> Comment out unused variables

.github/auto_assign.yml
Add auto-assign probot.
https://github.com/kentaro-m/auto-assign/
https://probot.github.io/apps/auto-assign/
=> Add auto-assign

.github/reaction.yml
Add reaction bot
https://github.com/dessant/reaction-comments
https://probot.github.io/apps/reaction/
=> Add reaction bot

compose/.apps/samba/samba.aarch64.yml, compose/.apps/samba/samba.armv7l.yml
See title
https://hub.docker.com/r/dperson/samba/tags
=> Add ARM images for samba

compose/.apps/filebot/filebot.hostname.yml, compose/.apps/filebot/filebot.labels.yml, compose/.apps/filebot/filebot.netmode.yml, compose/.apps/filebot/filebot.ports.yml, compose/.apps/filebot/filebot.x86_64.yml, compose/.apps/filebot/filebot.yml
This closes #557 
Add the required files.
```bash
ds -u origin/filebot
ds -a filebot
```
https://github.com/jlesage/docker-filebot
https://hub.docker.com/r/jlesage/filebot
=> Add FileBot

.scripts/run_python.sh
Allow use of python3.8
https://devguide.python.org/#status-of-python-branches
=> Add support for python3.8

compose/.apps/plex/plex.labels.yml, compose/.apps/plex/plex.yml
**Purpose**
LSIO now supports Plex tokens.
**Learning**
https://github.com/linuxserver/docker-plex/pull/214
=> Add plex_claim and remove transcode volume

.editorconfig, .scripts/backup_create.sh
**Purpose**
Add an editorconfig and resolve a minor issue with shfmt testing.
**Learning**
https://github.com/mvdan/sh/releases/tag/v3.0.0
=> Shfmt and Editorconfig

compose/.apps/librespeed/librespeed.aarch64.yml, compose/.apps/librespeed/librespeed.armv7l.yml, compose/.apps/librespeed/librespeed.hostname.yml, compose/.apps/librespeed/librespeed.labels.yml, compose/.apps/librespeed/librespeed.netmode.yml, compose/.apps/librespeed/librespeed.ports.yml, compose/.apps/librespeed/librespeed.x86_64.yml, compose/.apps/librespeed/librespeed.yml
**Purpose**
Add new app LibreSpeed
**Approach**
Add the required files.
**Learning**
https://github.com/linuxserver/docker-librespeed
=> Add librespeed

compose/.apps/limnoria/limnoria.aarch64.yml, compose/.apps/limnoria/limnoria.armv7l.yml, compose/.apps/limnoria/limnoria.hostname.yml, compose/.apps/limnoria/limnoria.labels.yml, compose/.apps/limnoria/limnoria.netmode.yml, compose/.apps/limnoria/limnoria.ports.yml, compose/.apps/limnoria/limnoria.x86_64.yml, compose/.apps/limnoria/limnoria.yml
**Purpose**
Add limnoria
**Learning**
https://hub.docker.com/r/linuxserver/limnoria
=> Add limnoria

compose/.apps/limnoria/limnoria.ports.yml
**Purpose**
Used the wrong port.
**Approach**
Use port 8080
=> Fix limnoria port

.scripts/appvars_create.sh, .scripts/install_yq.sh, .scripts/menu_app_select.sh, .scripts/menu_value_prompt.sh, .scripts/yml_get.sh
**Purpose**
This essentially undid most of https://github.com/GhostWriters/DockSTARTer/pull/848
Apparently 3.0.x operated in ways that were not expected/intended.
3.1.x seems to resolve that and the behavior has returned to how it was on 2.x
This is a more permanent replacement for https://github.com/GhostWriters/DockSTARTer/pull/869 and properly fixes https://github.com/GhostWriters/DockSTARTer/issues/868
=> Update to yq 3.1.0

compose/.apps/minecraft_bedrock_server/minecraft_bedrock_server.hostname.yml, compose/.apps/minecraft_bedrock_server/minecraft_bedrock_server.labels.yml, compose/.apps/minecraft_bedrock_server/minecraft_bedrock_server.netmode.yml, compose/.apps/minecraft_bedrock_server/minecraft_bedrock_server.ports.yml, compose/.apps/minecraft_bedrock_server/minecraft_bedrock_server.x86_64.yml, compose/.apps/minecraft_bedrock_server/minecraft_bedrock_server.yml, compose/.apps/minecraft_server/minecraft_server.aarch64.yml, compose/.apps/minecraft_server/minecraft_server.armv7l.yml, compose/.apps/minecraft_server/minecraft_server.hostname.yml, compose/.apps/minecraft_server/minecraft_server.labels.yml, compose/.apps/minecraft_server/minecraft_server.netmode.yml, compose/.apps/minecraft_server/minecraft_server.ports.yml, compose/.apps/minecraft_server/minecraft_server.x86_64.yml, compose/.apps/minecraft_server/minecraft_server.yml
**Purpose**
Add Minecraft Java and Bedrock Servers
**Learning**
https://hub.docker.com/r/itzg/minecraft-server
https://www.github.com/itzg/docker-minecraft-server
https://hub.docker.com/r/itzg/minecraft-bedrock-server
https://www.github.com/itzg/docker-minecraft-bedrock-server
=> Add Minecraft Java and Bedrock Servers

compose/.apps/piwigo/piwigo.aarch64.yml, compose/.apps/piwigo/piwigo.armv7l.yml, compose/.apps/piwigo/piwigo.hostname.yml, compose/.apps/piwigo/piwigo.labels.yml, compose/.apps/piwigo/piwigo.netmode.yml, compose/.apps/piwigo/piwigo.ports.yml, compose/.apps/piwigo/piwigo.x86_64.yml, compose/.apps/piwigo/piwigo.yml
**Purpose**
This closes #721 
**Approach**
Add the files for piwigo.
**Learning**
https://hub.docker.com/r/linuxserver/piwigo/
=> Add piwigo

.scripts/install_compose.sh
**Purpose**
This probably fully resolves some CentOS and omv install issues.
This is recommend by the official Linux install docs from docker.
**Learning**
https://docs.docker.com/compose/install/
=> Symlink compose

.scripts/update_self.sh
**Purpose**
Speed up upgrades by grouping files with `xargs` instead of looping over each one.
=> Set repo permissions more efficiently

compose/.apps/deemix/deemix.aarch64.yml, compose/.apps/deemix/deemix.armv7l.yml, compose/.apps/deemix/deemix.hostname.yml, compose/.apps/deemix/deemix.labels.yml, compose/.apps/deemix/deemix.netmode.yml, compose/.apps/deemix/deemix.ports.yml, compose/.apps/deemix/deemix.x86_64.yml, compose/.apps/deemix/deemix.yml
**Purpose**
Added "Deemix". Application for downloading music from Deezer. Successor to deezloader rmx which was discontinued.
**Approach**
Website with login and search functionality
-
- [x ] Use github checklists. When solved, check the box and explain the answer.
**Learning**
-
-
- [x ] These changes meet the standards for [contributing](https://github.com/GhostWriters/DockSTARTer/blob/master/.github/CONTRIBUTING.md).
- [x ] I have read the [code of conduct](https://github.com/GhostWriters/DockSTARTer/blob/master/.github/CODE_OF_CONDUCT.md).
=> [ADD] Deemix

main.sh
**Purpose**
Attempt to resolve permission issues with log file on new installs.
**Approach**
Use `mktemp` for the log file location. `chown` the log file every time the `log` function is run.
```
cd ~/.docker
git fetch -p
git reset --hard origin/log
cd ~/
ds -fiv
```
=> Write log to mktemp

compose/.apps/deemix/deemix.aarch64.yml, compose/.apps/deemix/deemix.armv7l.yml, compose/.apps/deemix/deemix.labels.yml, compose/.apps/deemix/deemix.ports.yml, compose/.apps/deemix/deemix.x86_64.yml
See #927 
Switched deemix container to gitlab.
=> Switched Deemix container after takedown

.scripts/update_self.sh
**Purpose**
`git gc` seems to be specifically designed to do what I was trying to accomplish with the original line, and more. It's a simpler solution and should do a better job overall.
**Approach**
Replace the custom code that removes extra branches with `git gc`.
**Learning**
https://git-scm.com/docs/git-gc
=> Use git gc to clean and optimize

compose/.apps/calibre/calibre.aarch64.yml, compose/.apps/calibre/calibre.armv7l.yml, compose/.apps/calibre/calibre.hostname.yml, compose/.apps/calibre/calibre.labels.yml, compose/.apps/calibre/calibre.netmode.yml, compose/.apps/calibre/calibre.ports.yml, compose/.apps/calibre/calibre.x86_64.yml, compose/.apps/calibre/calibre.yml
**Purpose**
Add Calibre since apparently you need more than just calibre web.
**Learning**
https://github.com/linuxserver/docker-calibre
https://hub.docker.com/r/linuxserver/calibre
=> Add calibre

.gitignore
**Purpose**
This file is used by docker desktop on Windows. This is a rabbit hole that might lead (later) to a bigger change being considered.
=> Ignore credentials file config.json

compose/.apps/bitwarden/bitwarden.aarch64.yml, compose/.apps/bitwarden/bitwarden.armv7l.yml
**Purpose**
Use the new multiarch images. (wait for them to publish on docker hub https://hub.docker.com/r/bitwardenrs/server/tags )
**Learning**
https://github.com/dani-garcia/bitwarden_rs/releases/tag/1.16.0
=> Multiarch bitwarden_rs

docs/apps/samba.md
**Purpose**
Adding further documentation to the Samba docs.
=> Updating Samba Docs

docs/apps/xbackbone.md
**Purpose**
Added simple documentation for XBackBone
=> XBackBone Documentation

docs/apps/dozzle.md
**Purpose**
Initial documentation for Dozzle.
=> Dozzle Documentation

docs/apps/samba.md
**Purpose**
**Approach**
**Learning**
=> Updating Samba Docs - Yet Again

docs/apps/codeserver.md
**Purpose**
**Approach**
**Learning**
=> Small formatting change

docs/apps/samba.md
**Purpose**
**Approach**
**Learning**
=> Samba docs

docs/apps/hydra2.md, docs/apps/mcmyadmin2.md, docs/apps/plexrequests.md, docs/apps/ttrss.md, docs/apps/unifi.md
**Purpose**
Redirect pages with recommended replacements. Document when no replacement is available.
=> Update deprecation docs

.github/workflows/stale.yml
**Purpose**
Define exactly when things are stale and closed. Allow labels to keep things exempt from being stale.
**Learning**
https://github.com/actions/stale
=> Extra paramenters for stale

.github/workflows/label.yml, compose/.apps/photoshow/photoshow.aarch64.yml, compose/.apps/photoshow/photoshow.armv7l.yml, compose/.apps/photoshow/photoshow.hostname.yml, compose/.apps/photoshow/photoshow.labels.yml, compose/.apps/photoshow/photoshow.netmode.yml, compose/.apps/photoshow/photoshow.ports.yml, compose/.apps/photoshow/photoshow.x86_64.yml, compose/.apps/photoshow/photoshow.yml, docs/apps/photoshow.md, mkdocs.yml
**Purpose**
Closes #974 
**Approach**
**Learning**
=> Added Photoshow & Photoshow Documentation

compose/.apps/tdarr/tdarr.hostname.yml, compose/.apps/tdarr/tdarr.labels.yml, compose/.apps/tdarr/tdarr.netmode.yml, compose/.apps/tdarr/tdarr.ports.yml, compose/.apps/tdarr/tdarr.x86_64.yml, compose/.apps/tdarr/tdarr.yml, docs/apps/tdarr.md
**Purpose**
Closes #874 
**Approach**
**Learning**
=> Added Tdarr & Tdarr Documentation

compose/.apps/photoshow/photoshow.labels.yml, compose/.apps/photoshow/photoshow.ports.yml
**Purpose**
Fixes #1016 
**Approach**
It fixes it
**Learning**
=> Correct ports and labels for Photoshow

docs/apps/pihole.md
**Purpose**
**Approach**
**Learning**
=> Fixing some markdown on pihole.md

docs/basics/faq.md
**Purpose**
Adds Dozzle to the FAQ.
**Approach**
**Learning**
=> Updating FAQ to include Dozzle

compose/.apps/speedtest/speedtest.labels.yml, compose/.apps/speedtest/speedtest.yml
**Purpose**
speedtest updated the eula environment variable
the current eula variable doesn't exist so speedtest doesn't actually run
**Approach**
update the variable so that the speedtest is run and logged
**Learning**
https://github.com/henrywhitaker3/Speedtest-Tracker
=> Update speedtest eula environment variable

docs/basics/support.md
Documentation change to support.md
=> [minor] Fix strange capitalization and wording

README.md
=> Add pacman command to alternative install

compose/.apps/bitwarden/bitwarden.labels.yml, compose/.apps/bitwarden/bitwarden.ports.yml, compose/.apps/bitwarden/bitwarden.yml
**Purpose**
**Approach**
**Learning**
=> Add websocket variable to bitwarden

compose/.apps/swag/swag.labels.yml, compose/.apps/swag/swag.yml
**Purpose**
**Approach**
**Learning**
=> Add MMDB variable to SWAG

.github/workflows/CI.yml
This tries to use the manifest inspect command to validate the image is there
=> Validate All Docker Images Exist Every Run

docs/basics/faq.md
**Purpose**
**Approach**
**Learning**
=> Grammar fix

.scripts/install_compose_completion.sh, .scripts/install_machine_completion.sh
=> Create /etc/bash_completion.d/ if it does not exist

compose/.apps/tdarr/tdarr.labels.yml
**Purpose**
**Approach**
**Learning**
=> Changing default for TDARR_DB

compose/.apps/calibre/calibre.labels.yml, compose/.apps/calibre/calibre.yml
**Purpose**
**Approach**
**Learning**
=> Adding dark mode to Calibre

.github/workflows/validate.yml, docs/apps/calibre.md, docs/apps/traktarr.md, docs/apps/youtubedl.md, mkdocs.yml
**Purpose**
Confirm that every app in the repo has documentation, and the doc is linked in the nav.
=> Validate docs

compose/.apps/adguard/adguard.aarch64.yml, compose/.apps/adguard/adguard.armv7l.yml, compose/.apps/adguard/adguard.hostname.yml, compose/.apps/adguard/adguard.labels.yml, compose/.apps/adguard/adguard.netmode.yml, compose/.apps/adguard/adguard.ports.yml, compose/.apps/adguard/adguard.x86_64.yml, compose/.apps/adguard/adguard.yml, docs/apps/adguard.md, mkdocs.yml
**Purpose**
Add Adguard
**Learning**
https://hub.docker.com/r/adguard/adguardhome
https://github.com/AdguardTeam/AdGuardHome
=> Add Adguard

compose/.apps/transmissionvpn/transmissionvpn.aarch64.yml, compose/.apps/transmissionvpn/transmissionvpn.armv7l.yml
=> Fixed Transmission OpenVPN

compose/.apps/cloudflareddns/cloudflareddns.aarch64.yml, compose/.apps/cloudflareddns/cloudflareddns.armv7l.yml, compose/.apps/cloudflareddns/cloudflareddns.x86_64.yml
**Purpose**
**Approach**
**Learning**
=> Remove dashes from hotio images

docs/apps/unificontroller.md
**Purpose**
Some ELI5 for why we update the Controller's IP.
=> Updating UniFi Documentation

compose/.apps/openldap/openldap.aarch64.yml, compose/.apps/openldap/openldap.armv7l.yml, compose/.apps/openldap/openldap.hostname.yml, compose/.apps/openldap/openldap.labels.yml, compose/.apps/openldap/openldap.netmode.yml, compose/.apps/openldap/openldap.ports.yml, compose/.apps/openldap/openldap.x86_64.yml, compose/.apps/openldap/openldap.yml, docs/apps/openldap.md, mkdocs.yml
=> Adding OpenLDAP & Docs

compose/.apps/yacht/yacht.aarch64.yml, compose/.apps/yacht/yacht.armv7l.yml, compose/.apps/yacht/yacht.hostname.yml, compose/.apps/yacht/yacht.labels.yml, compose/.apps/yacht/yacht.netmode.yml, compose/.apps/yacht/yacht.ports.yml, compose/.apps/yacht/yacht.x86_64.yml, compose/.apps/yacht/yacht.yml, docs/apps/yacht.md, mkdocs.yml
=> Adding Yacht and Docs

compose/.apps/nodered/nodered.aarch64.yml, compose/.apps/nodered/nodered.armv7l.yml, compose/.apps/nodered/nodered.hostname.yml, compose/.apps/nodered/nodered.labels.yml, compose/.apps/nodered/nodered.netmode.yml, compose/.apps/nodered/nodered.ports.yml, compose/.apps/nodered/nodered.x86_64.yml, compose/.apps/nodered/nodered.yml, docs/apps/nodered.md, mkdocs.yml
=> Adding Node-RED & Docs

main.sh
**Purpose**
If tput is not available this should prevent a bunch of stderr for the user
**Approach**
Use `2> /dev/null` on tput commands
=> Send tput error to null

compose/.apps/picard/picard.hostname.yml, compose/.apps/picard/picard.labels.yml, compose/.apps/picard/picard.netmode.yml, compose/.apps/picard/picard.ports.yml, compose/.apps/picard/picard.x86_64.yml, compose/.apps/picard/picard.yml, docs/apps/picard.md, mkdocs.yml
Add MusicBrainz Picard to the DockerSTARTer list of apps.
=> Add MusicBrainz Picard to DS

docs/apps/watchtower.md
Cleaner with table and links to Shoutrrr if user needs more help
**Purpose**
**Approach**
**Learning**
=> Update watchtower.md (table) cleaner look

.scripts/install_compose.sh
**Purpose**
**Approach**
**Learning**
=> Remove previous compose images

.github/CONTRIBUTING.md, main.sh
**Purpose**
**Approach**
**Learning**
=> Remove references to Travis CI

compose/README.md, docs/advanced/macvlan.md, docs/advanced/technical-info.md, docs/apps/netdata.md, docs/apps/synclounge.md, docs/overrides/autoscan.md, docs/overrides/bw_plex.md, docs/overrides/dashmachine.md, docs/overrides/fireflyiii.md, docs/overrides/introduction.md, docs/overrides/kitana.md, docs/overrides/nginxproxymanager.md, docs/overrides/overseerr.md, docs/overrides/plpp.md, docs/overrides/requestrr.md, docs/overrides/yacreader.md
**Purpose**
**Approach**
**Learning**
=> Remove all references to compose version in overrides

.scripts/install_yq.sh
**Purpose**
**Approach**
**Learning**
=> Remove previous yq images

main.sh
**Purpose**
**Approach**
**Learning**
=> Truncate log

docs/overrides/conreq.md, docs/overrides/introduction.md, docs/overrides/overseerr.md, mkdocs.yml
**Purpose**
**Approach**
**Learning**
=> Add new override and update existing overrides

compose/.apps/filebrowser/filebrowser.labels.yml
**Purpose**
**Approach**
**Learning**
=> Fix filebrowser baseurl

compose/.apps/influxdb/influxdb.aarch64.yml, compose/.apps/influxdb/influxdb.armv7l.yml, compose/.apps/influxdb/influxdb.x86_64.yml
**Purpose**
Prevents InfluxDB 2.0 from being pulled and limits InfluxDB version to 1.8 as it breaks a lot of existing apps
**Learning**
=> Preventing InfluxDB 2.0 Update

.scripts/menu_config.sh
**Purpose**
**Approach**
**Learning**
=> Add descriptions to config menu

docs/overrides/petio.md, mkdocs.yml
Overrides for Petio thnx to mouzzampk2014
**Purpose**
Added Override for Petio
**Approach**
Added Override for Petio
**Learning**
=> Overrides for Petio

compose/.apps/bitwarden/bitwarden.aarch64.yml, compose/.apps/bitwarden/bitwarden.armv7l.yml, compose/.apps/bitwarden/bitwarden.x86_64.yml, docs/apps/bitwarden.md, docs/apps/vaultwarden.md, mkdocs.yml
**Purpose**
**Approach**
**Learning**
=> Changing image name for Bitwarden to Vaultwarden

main.sh
**Purpose**
Cleanup temp log file.
=> Remove tmp log

compose/.apps/adminer/adminer.aarch64.yml, compose/.apps/adminer/adminer.armv7l.yml, compose/.apps/adminer/adminer.hostname.yml, compose/.apps/adminer/adminer.labels.yml, compose/.apps/adminer/adminer.netmode.yml, compose/.apps/adminer/adminer.ports.yml, compose/.apps/adminer/adminer.x86_64.yml, compose/.apps/adminer/adminer.yml, docs/apps/adminer.md, mkdocs.yml
**Purpose**
Add the required files to run Adminer.
**Learning**
https://hub.docker.com/_/adminer/
https://github.com/vrana/adminer
https://www.adminer.org/
=> Add Adminer

docs/apps/jackett.md
**Purpose**
**Approach**
**Learning**
=> add explanation for VPN and private servers

main.sh
Resolve https://www.shellcheck.net/wiki/SC2294
=> Rewrite run_test

compose/.apps/delugevpn/delugevpn.x86_64.yml, compose/.apps/qbittorrentvpn/qbittorrentvpn.x86_64.yml, compose/.apps/rtorrentvpn/rtorrentvpn.x86_64.yml, compose/.apps/sabnzbdvpn/sabnzbdvpn.x86_64.yml
**Purpose**
ghcr does not have pull limits.
**Learning**
https://github.com/binhex/arch-delugevpn/pkgs/container/arch-delugevpn
https://github.com/binhex/arch-qbittorrentvpn/pkgs/container/arch-qbittorrentvpn
https://github.com/binhex/arch-rtorrentvpn/pkgs/container/arch-rtorrentvpn
https://github.com/binhex/arch-sabnzbdvpn/pkgs/container/arch-sabnzbdvpn
=> Use ghcr for binhex images

docs/apps/homeassistant.md
**Purpose**
Adds extra troubleshooting documentation.
**Approach**
I found this is a very frequently asked question.
**Learning**
[HomeAssistant issue](https://github.com/home-assistant/core/issues/30357)
=> Adding network mode suggestion

compose/.apps/jfago/jfago.aarch64.yml, compose/.apps/jfago/jfago.armv7l.yml
**Purpose**
Arm images are available https://hub.docker.com/r/hrfee/jfa-go/tags
=> Add jfa-go arm images

compose/.apps/watchtower/watchtower.aarch64.yml, compose/.apps/watchtower/watchtower.armv7l.yml, compose/.apps/watchtower/watchtower.x86_64.yml
**Purpose**
See title
**Learning**
https://github.com/containrrr/watchtower/pkgs/container/watchtower
=> Use ghcr for watchtower

.scripts/pm_apt_repos.sh, .scripts/pm_yum_repos.sh
**Purpose**
Add verbosity to repo updates
=> Add verbosity to repo updates

docs/requirements.txt
Reverts GhostWriters/DockSTARTer#1465
=> Revert "Bump pygments from 2.11.2 to 2.12.0"

.scripts/pm_apt_install_docker.sh, .scripts/pm_dnf_install_docker.sh, .scripts/pm_yum_install_docker.sh, .scripts/require_docker.sh
**Purpose**
[Fix docker and compose version detection](https://github.com/GhostWriters/DockSTARTer/commit/5044a53d99e39c4083af4de2dbe2a4da10533fc2)
[get.docker.com now installs docker-compose-plugin](https://github.com/GhostWriters/DockSTARTer/commit/99ee902dbe18b87dd934122303d347424b85b18f)
**Learning**
https://github.com/docker/docker-install/pull/288/commits/90d0bdf7b649221405bbc7fc9cabc1738d346cec
=> Fix docker and compose install

.scripts/update_self.sh
**Purpose**
Ensure folders inside repo are owned by the user.
=> Take ownership of repo folders

docs/overrides/fireflyiii.md
**Purpose**
The current image used in the example docker-compose is a personal image whose owner might not related to the firefly iii project.
**Approach**
Replace with official firefly iii docker hub repository
**Open Questions and Pre-Merge TODOs**\
**Learning**
[Firefly documentation](https://docs.firefly-iii.org/firefly-iii/installation/docker/)
=> Update Firefly III docker-compose sample to official image

compose/.apps/timemachine/timemachine.aarch64.yml, compose/.apps/timemachine/timemachine.armv7l.yml, compose/.apps/timemachine/timemachine.hostname.yml, compose/.apps/timemachine/timemachine.labels.yml, compose/.apps/timemachine/timemachine.netmode.yml, compose/.apps/timemachine/timemachine.ports.yml, compose/.apps/timemachine/timemachine.x86_64.yml, compose/.apps/timemachine/timemachine.yml, docs/apps/timemachine.md, mkdocs.yml
Signed-off-by: Matt Bentley <mbentley@mbentley.net>
**Purpose**
Closes #1344 
**Approach**
Adds `mbentley/timemachine`
**Learning**
=> Added timemachine; fixes #1344

.github/CONTRIBUTING.md
**Purpose**
Let's streamline contributions. When I added "homer" app support recently in PR #1489 I had to learn how to setup my dev environment and then how to a add new app. I want to document the process to help others.
=> Including CONTRIBUTING.md write-ups for setting up your dev environment, adding a new app, and markdown files

docs/overrides/dashmachine.md
**Purpose**
I think the Dashmachine override page has the wrong description
**Approach**
**Learning**
=> Fixed dashmachine.md

compose/.apps/gitea/gitea.armv7l.yml, compose/.apps/gitea/gitea.hostname.yml, compose/.apps/gitea/gitea.labels.yml, compose/.apps/gitea/gitea.netmode.yml, compose/.apps/gitea/gitea.ports.yml, compose/.apps/gitea/gitea.x86_64.yml, compose/.apps/gitea/gitea.yml, docs/apps/gitea.md, mkdocs.yml
**Purpose**
Adding Gitea
**Approach**
Added Gitea
=> Added Gitea

compose/.apps/delugevpn/delugevpn.yml, compose/.apps/nzbgetvpn/nzbgetvpn.yml, compose/.apps/rtorrentvpn/rtorrentvpn.yml, compose/.apps/sabnzbdvpn/sabnzbdvpn.yml
**Purpose**
This closes https://github.com/GhostWriters/DockSTARTer/issues/1533
**Approach**
Use `privileged` mode on all. Add wireguard configurations to nzbgetvpn.
=> Make all binhex vpn images consistent

.github/workflows/lint.yml
Causes false positives
**Learning**
https://github.com/markdownlint/markdownlint/blob/main/docs/RULES.md#md007---unordered-list-indentation
https://github.com/markdownlint/markdownlint/issues/313
=> Ignore MD007

compose/.apps/flame/flame.aarch64.yml, compose/.apps/flame/flame.labels.yml
**Purpose**
Sorry I must've missed this
=> Fixing Flame

compose/.apps/smokeping/smokeping.labels.yml
**Purpose**
Smokeping's description is currently incorrect, looks like it was copy/pasted from another tool. This PR resolves that with an appropriate description
**Approach**
Changes the description to one that actually matches Smokeping's functionality
**Learning**
Derived description from [Smokeping's GitHub repo](https://github.com/oetiker/SmokePing).
=> Update Smokeping description

mkdocs.yml
Source: https://squidfunk.github.io/mkdocs-material/upgrade/#contentcodecopy
**Purpose**
**Approach**
**Learning**
=> Fixed: "Copy To Clipboard" Icon on Code Blocks

compose/.apps/fail2ban/fail2ban.aarch64.yml, compose/.apps/fail2ban/fail2ban.armv7l.yml, compose/.apps/fail2ban/fail2ban.hostname.yml, compose/.apps/fail2ban/fail2ban.labels.yml, compose/.apps/fail2ban/fail2ban.netmode.yml, compose/.apps/fail2ban/fail2ban.x86_64.yml, compose/.apps/fail2ban/fail2ban.yml, docs/apps/fail2ban.md, mkdocs.yml
=> Add fail2ban

.github/workflows/validate.yml
**Purpose**
**Approach**
**Learning**
=> Replace docker manifest inspect with mquery

compose/.apps/homebridge/homebridge.aarch64.yml, compose/.apps/homebridge/homebridge.armv7l.yml, compose/.apps/homebridge/homebridge.hostname.yml, compose/.apps/homebridge/homebridge.labels.yml, compose/.apps/homebridge/homebridge.netmode.yml, compose/.apps/homebridge/homebridge.ports.yml, compose/.apps/homebridge/homebridge.x86_64.yml, compose/.apps/homebridge/homebridge.yml, docs/apps/homebridge.md, mkdocs.yml
**Purpose**
Add Homebridge as a new application.
Uses the Homebridge Docker containers recommended on the [Homebridge GitHub project](https://github.com/homebridge/homebridge/wiki/Install-Homebridge-on-Docker).
Continues PR #1421.
**Approach**
N/A
**Learning**
N/A
=> Add Homebridge

docs/apps/recyclarr.md
Shamelessly copied the text from the Bitwarden Install/Setup ;)
**Purpose**
**Approach**
**Learning**
=> Add note to change appdata/recyclarr ownership

compose/.apps/airdcpp/airdcpp.labels.yml, compose/.apps/airsonic/airsonic.labels.yml, compose/.apps/booksonic/booksonic.labels.yml, compose/.apps/couchpotato/couchpotato.labels.yml, compose/.apps/muximux/muximux.labels.yml, compose/.apps/nzbget/nzbget.labels.yml, compose/.apps/nzbgetvpn/nzbgetvpn.labels.yml, compose/.apps/photoshow/photoshow.labels.yml, compose/.apps/pyload/pyload.aarch64.yml, compose/.apps/pyload/pyload.armv7l.yml, compose/.apps/pyload/pyload.labels.yml, compose/.apps/pyload/pyload.ports.yml, compose/.apps/pyload/pyload.x86_64.yml, compose/.apps/requestrr/requestrr.labels.yml, docs/apps/pyload.md, mkdocs.yml
**Purpose**
**Approach**
**Learning**
=> Deprecations

compose/.apps/cloudflareddns/cloudflareddns.aarch64.yml, compose/.apps/cloudflareddns/cloudflareddns.x86_64.yml, compose/.apps/duplicacy/duplicacy.aarch64.yml, compose/.apps/duplicacy/duplicacy.x86_64.yml, compose/.apps/unpackerr/unpackerr.aarch64.yml, compose/.apps/unpackerr/unpackerr.x86_64.yml, docs/overrides/introduction.md, docs/overrides/overseerr.md, docs/overrides/petio.md
**Purpose**
Closes #1715 
**Approach**
Updates cr.hotio.dev to ghcr.io
**Learning**
=> Updating cr.hotio.dev to ghcr.io

docs/apps/homepage.md, docs/apps/nextcloud.md, docs/apps/pgbackup.md, docs/apps/postgres.md
**Purpose**
**Approach**
**Learning**
=> chore: fix some comments

compose/.apps/komga/komga.labels.yml, compose/.apps/komga/komga.ports.yml
**Purpose**
**Approach**
**Learning**
=> fix: `komga` using wrong port

compose/.apps/jellyseerr/jellyseerr.aarch64.yml, compose/.apps/jellyseerr/jellyseerr.hostname.yml, compose/.apps/jellyseerr/jellyseerr.labels.yml, compose/.apps/jellyseerr/jellyseerr.netmode.yml, compose/.apps/jellyseerr/jellyseerr.ports.yml, compose/.apps/jellyseerr/jellyseerr.x86_64.yml, compose/.apps/jellyseerr/jellyseerr.yml, docs/apps/jellyseerr.md, mkdocs.yml
**Purpose**
Add the Jellyseerr app to DockStarter
**Approach**
It adds the Jellyseerr app to DS
**Learning**
N/A
=> Jellyseerr

compose/.apps/actualbudget/actualbudget.aarch64.yml, compose/.apps/actualbudget/actualbudget.hostname.yml, compose/.apps/actualbudget/actualbudget.labels.yml, compose/.apps/actualbudget/actualbudget.netmode.yml, compose/.apps/actualbudget/actualbudget.ports.yml, compose/.apps/actualbudget/actualbudget.x86_64.yml, compose/.apps/actualbudget/actualbudget.yml, docs/apps/actualbudget.md, mkdocs.yml
**Purpose**
This PR adds [Actual Budget](https://actualbudget.org), a modern, open-source personal finance tool for budgeting and expense tracking.
Closes #1837 
**Approach**
- Integrated Actual Budget into DockSTARTer, making it available for users to install directly from the app.
- Added configuration options and documentation for setup.
**Learning**
- Reviewed Actual Budget’s [official documentation](https://actualbudget.org/docs) and [Github](https://github.com/actualbudget/actual) sites for installation and deployment requirements.
- Looked at [community Docker images](https://hub.docker.com/r/actualbudget/actual-server) for deployment best practices.
=> ✨ feat(apps): add Actual Budget

.scripts/update_self.sh
**Purpose**
**Approach**
**Learning**
=> Fix update

main.sh
**Purpose**
**Approach**
**Learning**
=> Fix the `ds -u branch` option.

compose/.apps/readarr/readarr.labels.yml
**Purpose**
**Approach**
**Learning**
=> Depreciate `Readarr`

main.sh
**Purpose**
**Approach**
**Learning**
=> Remove debugging notice

.scripts/menu_value_prompt.sh
**Purpose**
**Approach**
**Learning**
=> Add blank lines after headings in `menu_value_prompt`

.scripts/ds_version.sh
**Purpose**
**Approach**
**Learning**
=> Use `<branch> <tag>`  or `<branch> commit <commit>` as the DS version

.scripts/update_self.sh
**Purpose**
**Approach**
**Learning**
=> Make `ds -u` skip updating if no update is needed.

.scripts/apply_theme.sh, .scripts/docker_compose.sh, .scripts/ds_update_available.sh, .scripts/ds_version.sh, .scripts/menu_add_var.sh, .scripts/menu_display_options.sh, .scripts/menu_main.sh, .scripts/menu_value_prompt.sh, .scripts/run_install.sh, .scripts/symlink_ds.sh, .scripts/update_self.sh, main.sh
**Purpose**
**Approach**
**Learning**
=> Use `${APPLICATION_NAME}` instead of `DockSTARTer`

.themes/BlackandWhite/theme.ini, .themes/Debian/theme.ini, .themes/DockSTARTer/theme.ini, .themes/Firehouse/theme.ini, .themes/GreenScreen/theme.ini, .themes/MagentaRise/theme.ini, .themes/Marigold/theme.ini, .themes/Murica/theme.ini, .themes/Summertime/theme.ini, .themes/WhiptailRipoff/theme.ini, main.sh
**Purpose**
**Approach**
**Learning**
=> Add theming to all backtitle elements

.scripts/menu_dialog_example.sh
**Purpose**
**Approach**
**Learning**
=> Fix backtitle not showing for dialog box example.

main.sh
**Purpose**
**Approach**
**Learning**
=> Move the application and version info down in the usage text.

main.sh
Change the version notice to an info.
Move it up slightly in the main function, and put the update notice directly after it.
**Purpose**
**Approach**
**Learning**
=> Change version `notice` to an `info`.

.scripts/update_self.sh
**Purpose**
**Approach**
**Learning**
=> Fix logic when deciding what to show when updating to the same branch

main.sh
**Purpose**
**Approach**
**Learning**
=> Split update notice to two lines

main.sh
**Purpose**
**Approach**
**Learning**
=> Return at error notice for `ds --version` if the branch does not exist

.scripts/question_prompt.sh
**Purpose**
**Approach**
**Learning**
=> Strip ANSI colors from dialog boxes in `question_prompt`

main.sh
**Purpose**
**Approach**
**Learning**
=> Move `--select` option below the `env_create` call

.scripts/menu_app_select.sh
**Purpose**
**Approach**
**Learning**
=> Update the progress dialog screens in `menu_app_select`

.themes/DockSTARTer/.dialogrc
**Purpose**
**Approach**
**Learning**
=> Reverse the gauge colors for the DockSTARTer theme

.scripts/pm_nala_upgrade.sh
**Purpose**
**Approach**
**Learning**
=> Fix incorrect `nala full-upgrade -y` command to `nala upgrade --full -y`

.includes/usage.sh
**Purpose**
**Approach**
**Learning**
=> Fix the incorrect usage text for `ds --menu select`

.scripts/app_nicename.sh, .scripts/app_nicename_from_template.sh
**Purpose**
**Approach**
**Learning**
=> Add unit tests for `app_nicename` and `app_nicename_from_template`
