GhostWriters/DockSTARTer

compose/.apps/portainer/portainer.yml

Removed TZ as not supported by Portainer and replaced with /etc/localtime:/etc/localtime:ro

Portainer timefix

---

.travis.yml

This thing is just needlessly chatty and you still need to actually go to Travis and read the logs even when it comments about failure because it doesn't comment any part of the log. It looks promising on paper but doesn't seem complete.

Disable Travis Buddy

---

scripts/root_check.sh

This caused an issue running without root. Downside is it won't show which options you ran with. Prior behavior wasn't right with this anyway.
I ran `main.sh -g` and it asked me to run `sudo main.sh -g` (good)
I ran `main.sh --fake -g` and it asked me to run `sudo main.sh --fake` (bad, missing `-g`)
I adjusted `${ARGS}` to `${ARGS[@]}` and also tried `${ARGS[*]}` and both resulted in the following:
I ran `main.sh --fake -g` and it asked me to run
```
sudo main.sh --fake
-g
```
(bad, newline for each arg)
***
So my conclusion was to just remove ARGS entirely at least for now.
Result is I ran `main.sh -g` and it asked me to run `sudo main.sh` (good enough for now)

Fix root check

---

compose/.apps/tautulli/tautulli.yml

This caused the folders to actually have slashes in them...

Remove slashes from Tautulli Plex Logs folder.

---

scripts/cmd_install.sh
scripts/run_compose.sh
scripts/set_permissions.sh

This should be usable with every folder prompt in the GUI (like downloads and media folders). There is an example below of using this without any parameters (install just defaults to chmod on script path) and also one in the compose function that passes in the environment variables.

Add set_permissions function

---

scripts/env_set.sh

More GUI prep, to make sure the GUI branch can rebase/squash easily.
Previous behaviour was unhappy handling timezones because of the `/` character. This resolves by escaping.

Fix env_set to handle escaping

---

scripts/menus/application_selector.sh
scripts/menus/config_folder_set.sh
scripts/menus/download_folder_set.sh
scripts/menus/input_prompt.sh
scripts/menus/media_folders_set.sh
scripts/menus/menu_main.sh
scripts/menus/timezone_set.sh
scripts/menus/user_group_set.sh
scripts/request_reboot.sh
scripts/run_compose.sh
scripts/update_self.sh

So this is kind of a quality of life change. We have discussed previously that it's a bit jarring to be bounced between the whiptail menus and the terminal, but I feel like this helps that a little bit by resetting the console immediately after any whiptail menu is shown thus you get a nice clean console and don't watch what's left of the whiptail menu float upward as the console slowly adds more lines. There's still the back and forth between menus and console, but at least it's cleaner.

Reset screen after whiptails

---

scripts/generate_yml.sh
scripts/install_docker.sh

The docker install shell script was being left behind at times. This was likely due to the trap command so I replaced all trap commands.

Remove trap commands and prevent leftovers on the spot

---

compose/.apps/emby/emby.arm64.yml
compose/.apps/portainer/portainer.arm64.yml
compose/.apps/watchtower/watchtower.arm64.yml

Emby, Portainer, and Watchtower do not have aarch64 images. These files should be removed since they are redundant to the armhf files which are used automatically on aarch64 systems when needed.
Remove the files that are not needed because the generator pulls armhf images for aarch64 systems if there is no aarch64 yml file.

Remove redundant aarch64 yml

---

scripts/update_self.sh

I noticed that the update function was fetching the remote changes (from the master branch of the repo) but not actually applying them to the locally checked out master branch.
After doing a hard reset (which we were already going) a pull should run without issue and either actually pull or do nothing if there are no updates.
https://stackoverflow.com/questions/1125968/how-do-i-force-git-pull-to-overwrite-local-files
https://stackoverflow.com/questions/6335681/git-how-do-i-get-the-latest-version-of-my-code
Per the answers in these two discussions it looks like others trying to accomplish the same thing are using similar methods. The key difference is that some of the answers instruct how to get the branch clean so that a pull can be performed but the examples they provide do not actually …

Include git pull in update_self

---

scripts/menu_app_select.sh
scripts/menu_value_prompt.sh

`true` and `false` do not need to be quoted. Some places in the code were quoting it and some places were not. This removes the quotes and keeps consistent across the board.
Remove the quotes around true or false.

Unquote true and false

---

scripts/run_compose.sh

Run compose as the user running DS. This is safer than running as root (which is what we currently do). Docker itself still runs via systemd and is setup to run as whatever user the official get.docker.com script configures.
Use `su -c`. Has been fully tested by myself and others.

Run compose as detected uname

---

README.md

Add beerpay.io to the readme. 
Beerpay lists all contributors to the repo as optional recipients and supporters can choose who to donate to. Supporters can also choose to put a wish (bounty) on a specific issue on GitHub and I think whoever closes the issue gets the bounty. Contributors will need to sign up for beerpay.io and link a Stripe account in order to receive donations from Supporters.
https://beerpay.io/GhostWriters/DockSTARTer

Add beerpay.io to README.md

---

main.sh
tests/validate_shellcheck.sh

Since Codacy now seems to have all validations from Shellcheck 0.5.0 builds will fail there until this is merged.
Use directives as described in Shellcheck's wiki to let Shellcheck know what we're doing with source files. The ones that source based on parameter input will use /dev/null while any that point to a permanent location will use that in the directive relative to the path of the script containing the directive.
https://github.com/koalaman/shellcheck/wiki/SC1090
https://github.com/koalaman/shellcheck/wiki/SC1091
https://github.com/koalaman/shellcheck/wiki/Directive

Use shellcheck directives with sourcing

---

scripts/env_get.sh

Follow up to the emergency fix. This could be affected the same way, so the same fix is needed.
Use proper regex with grep for env_get

Apply regex fix to env_get

---

.github/stale.yml

We're currently using the enhancement label for issues or pull requests involving new features. Allowing them to become stale should result in email notifications so that we can determine if the issue/PR is being actively worked on or if it has been abandoned. New activity after a stale notice would prevent the issue from being automatically closed.
See above.

Remove enhancement from stale exemption

---

scripts/run_compose.sh

Revisit https://feathub.com/GhostWriters/DockSTARTer/+14 and actually remove orphans using the build in option with compose. The prune option that was considered to resolve the request does not actually remove orphans, it only cleans up unused objects after the container is stopped. Without using the build in remove orphans option the container is left running.
Add the remove orphans option to compose up. This will Stop and remove a container that is no longer considered part of the stack. The existing prune option will clean up unused resources such as the image that the container used (this is not automatically removed when an orphan container is removed).
https://docs.docker.com/compose/reference/up/

Remove orphans with compose up

---

scripts/menu_app_select.sh

Some apps who's properly formatted names did not match the simplified names assigned in DS would cause errors when selected from menus.
Formatted names should match the APPNAME variable but can be different case (upper/lower).

Fix app menu formatting bug

---

compose/.apps/netdata/netdata.yml
compose/.env.example
main.sh
scripts/enable_docker_systemd.sh
scripts/install_compose.sh
scripts/install_compose_completion.sh
scripts/install_docker.sh
scripts/install_machine_completion.sh
scripts/install_yq.sh
scripts/setup_docker_group.sh

Netdata uses the docker group ID rather than the detected user group ID. We need a safe way to detect this and set it so it can be used in yml files as an environment variable.
- Add a new .env var `DOCKERGID`
- Change `setup_docker_group` to handle creating the group differently and set the new variable
https://github.com/jenkinsci/docker/issues/196#issuecomment-179486312

Better handling of Docker GID

---

compose/.apps/netdata/netdata.yml

Netdata will work with a config directory volume to `/etc/netdata`
Add the volume.
https://github.com/firehol/netdata/issues/4125#issuecomment-422157585

Add netdata config volume

---

main.sh
scripts/set_permissions.sh
scripts/update_system.sh

Travis should display a warning when a PR from a remote branch runs. The only time anyone will bother looking to see this warning is if the build fails, which can be caused by lack of GH tokens and the build might just need to rerun.
Add a warning message on clean up if we're running in travis without the secure vars (GH token). Also fixes some minor spelling errors.

Display a warning on Travis builds from remote branches

---

scripts/generate_yml.sh

`compose/docker-compose.sh` is leftover for some users occasionally with no warning. We should at least warn the user if the file is not removed.
Attempt to remove the file before creating it and include a fatal if it fails. Add an error (no exit) to the attempt at removing it after it's been run.

Remove runfile before attempting to create it

---

compose/.apps/bazarr/bazarr.arm64.yml
compose/.apps/bazarr/bazarr.armhf.yml
compose/.apps/bazarr/bazarr.yml

Switch DS to LSIO images for Bazarr
Change the existing files to use the new images
https://hub.docker.com/r/linuxserver/bazarr/
The above link will not work until the images are released and even then we should wait until Bazarr is listed on https://www.linuxserver.io/our-images/
LSIO's new build system uses a single repo with tags for multi-arch support, so we no longer use the separate arm images.

Use LSIO Bazarr images

---

.travis.yml
compose/.apps/airdcpp/airdcpp.ports.yml
main.sh
scripts/cmdline.sh
scripts/env_create.sh
tests/run_generate_full.sh

Fix AirDCpp port and Travis buids and exit codes.
- Fix spelling error with AirDCpp
- Adjust Travis builds to include an env var showing which test they are running
- Fix how exit codes are handled so that Travis builds actually fail
- Ensure that Travis is NOT pulling the master branch for each test

Aircdpp port

---

compose/.apps/heimdall/heimdall.arm64.yml
compose/.apps/heimdall/heimdall.armhf.yml

Use the new multi-arch images just released by LSIO for Heimdall.
Set all of the arch yml files to use the same image.
https://github.com/linuxserver/docker-heimdall/pull/9

Switch Heimdall to LSIO Multi-Arch

---

main.sh

The `-R` flag is unnecessary when running on a single file.
Remove it.

Remove -R from log chmod

---

tests/run_generate_full.sh

Fix port conflict in full generator tests.
Change port for mcmyadmin2
These two apps were added to DS in two separate branches at the same time, both were passing full builds in their own branches. When merging to master I must have overlooked the port conflict since they worked in their individual branches.

Fix port conflict in full tests

---

scripts/menu_value_prompt.sh

Fix tilde not matching.
Unquote it.
https://stackoverflow.com/a/2172367/1384186
```
[[ $a == z* ]] # True if $a starts with a "z" (wildcard matching).
[[ $a == "z*" ]] # True if $a is equal to z* (literal matching).
```

Fix tilde match

---

scripts/ui_config_globals.sh
scripts/ui_config_vpn.sh

Make the global and vpn vars show an overview screen like appears. Allow users to skip the whole section. Reorder a few prompts.
- Write a routine to put together the overview screen
- Add some logic to default yes or no for VPN based on whether the user has VPN apps enabled (so that pressing enter for the default on first run takes users to the right place
- Default no to keep globals so that users will set those on their first run

Rework prompts for global and vpn vars

---

scripts/menu_app_select.sh

This closes #305
Add some descriptive text to the app select menu about keys used to navigate.

Add keyboard instructions to app select menu

---

compose/.apps/organizr/organizr.armhf.yml
compose/.apps/organizr/organizr.yml

The organizr team has released a new repo for the v2 docker image
Replace the existing image with the new repo
https://hub.docker.com/r/organizrtools/organizr-v2/

New OrganizrTools repo

---

main.sh
scripts/env_backup.sh
scripts/env_create.sh
scripts/env_update.sh
scripts/menu_config.sh
scripts/menu_main.sh
scripts/prune_docker.sh
scripts/request_reboot.sh
scripts/run_compose.sh
scripts/ui_install.sh
scripts/update_self.sh

If we're running in menu mode it should just be known globally and not defined in each function.
Declare `PROMPT` as global using `readonly`. Remove individual functions `local PROMPT` lines. Remove `menu` from arguments on function calls.

Make PROMPT readonly

---

scripts/root_check.sh

If the users forgets sudo we should try to gracefully include it for them.
Rather than `fatal` we will try and run the script with sudo for the user. If they fail to enter the password correctly we will display the "run as root" message using fatal. Also improve the "run as root" message to include `ARGS` correctly.

Improve handling of root_check

---

scripts/run_compose.sh

Move the username in the su command to be more inline with the representation from the documentation
http://man7.org/linux/man-pages/man1/su.1.html

Format the su command a bit cleaner

---

main.sh

Running backups in `sudo crontab` would result in DS cloning it's repo to `/root/.docker` and making backups of `/root/.docker/config` regardless of the actual user who the script should be run as. Adding these checks will make it so that running DS with arguments will bypass the clone and run-from checks and allow backups and other operations to complete successfully.
Checks if ARGS are set before taking action that would clone the repo and run from another location.

Skip clone and run from different location if args are specified

---

main.sh
scripts/cmdline.sh
tests/run_generate_slim.sh

Add `-c` and `--compose` to reduce confusion. Eventually deprecate `-g`, but not with this PR.
Add the code required for -c and replace all references to -g but keep -g in cmdline until it is deprecated.

Replace -g/--generate with -c/--compose

---

compose/.apps/duckdns/duckdns.arm64.yml
compose/.apps/duckdns/duckdns.armhf.yml

This closes #343 
Replace the image used in the ARMHF and AARCH64 files with the new supported image.
https://hub.docker.com/r/linuxserver/duckdns/

Use new DuckDNS images for ARMHF/AARCH64

---

scripts/cmdline.sh
scripts/run_compose.sh

Since we have `-c`/`--compose` now we should allow options such as up/down and possibly others. Keep it simple, don't require common options to be specified, but possibly allow them to be specified (this may be overkill).

Add compose options

---

tests/run_generate_slim.sh

Use `docker-compose config` rather than just `cat` to confirm the compose file is valid.
https://docs.docker.com/compose/reference/config/

Use docker-compose config to validate yml

---

README.md
scripts/request_reboot.sh

Recent updates to the script to handle installing dependencies on first run allow us to reduce and rearrange the one time setup instructions.
Each system type (APT/DNF/YUM) will include instructions just to install `git` and then run DS which would install the remaining dependencies. The script will prompt for reboot, but in case the user selects not to reboot we will still include `sudo reboot` instructions in the readme.

Reduce one time setup instructions

---

compose/.apps/transmissionvpn/transmissionvpn.armhf.yml

This closes #222 
Haugene has added armhf images to his automated builds. We will include this option.
Add the yml template containing the image for transmissionvpn on armhf.
https://github.com/haugene/docker-transmission-openvpn/issues/571#issuecomment-436232687

Add armhf template for transmissionvpn

---

scripts/root_check.sh

Running without sudo would show an error even in circumstances where nothing was wrong. Ex: first run if the user elects not to reboot, choosing no would result in an error that the script much be run as root even though it already was.
Use a subshell and return true even if the script returns false. The script inside the subshell should handle reporting is there was an issue.

Root improvements

---

.scripts/install_compose.sh
.scripts/install_docker.sh
.scripts/install_yq.sh

We should test that the latest available version of the core dependencies (`docker`, `docker-compose`, and `yq`) are installed after their respective installation processes run.
Add a check in each installation function. Minor reordering of a few functions.
- The latest release of `docker` is not always available for every distro that is otherwise supported. Currently the check we use will result in unnecessary installation on systems that don't have an update available. After investigation I have not found a suitable way to resolve this issue. I will keep this note here but remove the checkbox as it is no longer actionable.

Test core installations after install

---

.scripts/cmdline.sh
.scripts/enable_docker_systemd.sh
main.sh

Simply and update usage and make it easier to find.
Move the usage comments to the top of `main.sh`, include up/down/restart/pull, move Arch church into main function, move Travis vars up, move systemd check to the only function that uses systemd.

Various cleanup and reordering

---

.tests/validate_bashate.sh
.tests/validate_shellcheck.sh

Validation skipping should be done by reading the top line of the file, not the file name.
Use the `head` command as it's used in https://github.com/caarlos0/shell-ci-build

Fix validations

---

.tests/run_generate_full.sh
.tests/validate_bashate.sh
.tests/validate_shellcheck.sh
.tests/validate_shfmt.sh
.travis.yml

Using the minimal Travis CI environment that comes with less preinstalled should help further prove that the scripts in the repo are doing their job.
Update the travis configuration. The minimal environment does not include mysql so we remove the code that handled stopping the mysql service.
https://docs.travis-ci.com/user/languages/minimal-and-generic/

Use minimal travis environment

---

.scripts/backup_max.sh

Fix `json: cannot unmarshal array into Go value of type types.ContainerJSON` error.
The `ls -a` was sending `.` and `..` into `docker inspect` which is where the error was coming from. We have switched to `ls -A` which excludes `.` and `..` and we have also suppressed the error messages and returned false if the command fails.

Fix unmarshal error

---

.travis.yml

Resolve broken builds since get.docker.com updated.
Switch to `xenial` builds on Travis CI.
https://docs.travis-ci.com/user/reference/xenial
https://blog.travis-ci.com/2018-11-08-xenial-release

Switch to xenial for Travis CI

---

main.sh

Address the source issue on CentOS 
CentOS and possibly others don't seem to do well with `$BASH_SOURCE` so we fall back on `$0`
https://stackoverflow.com/questions/35006457/choosing-between-0-and-bash-source

Source fix

---

.travis.yml

It seems Trusty isn't actually broken (yet). Not specifying the `dist` or OS lets the Travis build system decide what distro to build on. It might also make sense to setup travis to test both for stage 2, or split stage 2 into 2 and 3 where one would be Trusty and one would be Xenial.
This will probably remain open for a while until a decision is made about what direction to go with it.

Remove OS specification from Travis

---

main.sh

Backups being triggered via root cron were not running due to being blocked by our anti-run-as-root code. This resolves the issue by skipping the anti-run-as-root check when running in a non interactive shell.
Only run the root check when running in an interactive shell.
http://techdoc.kvindesland.no/linux/gnubooks/bash/bashref_54.html

Only root check with interactive shell

---

compose/.apps/deluge/deluge.arm64.yml
compose/.apps/deluge/deluge.armhf.yml

LSIO has discontinued the arch specific Deluge images and is now releasing multiarch images under `linuxserver/deluge`
Use the multiarch image in all templates.
https://hub.docker.com/r/linuxserver/deluge/

Use new multiarch Deluge image from LSIO

---

compose/.apps/plex/plex.yml

Keep original volumes as well so we don't break backwards compatibility, but let users use either one they prefer since the root ones are common to most other containers using media

Add root directory volumes for plex

---

compose/.env.example

This closes #443 
Allow the user to specify their own `COMPOSE_HTTP_TIMEOUT` if they ever see this
```
ERROR: An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).
```
Add the variable to .env but do not include it in the editable menus. This is an advanced option that normally should not need to be modified. If the user frequently has this issue there is likely another issue at play that should be addressed before encouraging users to adjust this.
https://docs.docker.com/compose/reference/envvars/#compose_http_timeout
https://stackoverflow.com/questions/36488209/how-to-override-the-default-value-of-com …

Add COMPOSE_HTTP_TIMEOUT

---

.scripts/install_compose.sh
.scripts/install_compose_completion.sh
.scripts/install_docker.sh
.scripts/install_machine_completion.sh
.scripts/install_yq.sh

This should give more clarification when PR builds fail or in general if the script is unable to complete a check for the latest available version of a particular dependency. Also correct some verbage (`docker compose` vs `docker-compose` etc).
Wrap certain curl commands in a subshell `()` and add the failure pipe to `fatal`.

Add logging for curl commands that check available versions

---

.scripts/install_compose.sh
.scripts/install_compose_completion.sh
.scripts/install_docker.sh
.scripts/install_machine_completion.sh
.scripts/install_yq.sh

Follow up to #460 since it did not actually work as expected. #460 did not cause any issues, but it did not accomplish the intended goal.
With #460 the `fatal` messages were suppressed inside the subshell rather than displayed to the console. This resolves the issue by moving the `fatal` piping to the end of the command which results in the intended logic of "Set this variable or else".

Proper fix for curl logging

---

.scripts/install_compose.sh
.scripts/install_yq.sh
.scripts/symlink_ds.sh

This closes #469 
CentOS (and maybe other OS) do not have `/usr/local/bin/` in their path variable, but do have `/usr/bin/`.
Symlink installed binaries from `/usr/local/bin/` to `/usr/bin/`. This is recommended by docker in the compose install documentation, and works for yq as well.
https://docs.docker.com/compose/install/
https://en.wikipedia.org/wiki/Unix_filesystem

Symlink to /usr/bin

---

compose/.apps/qbittorrentvpn/qbittorrentvpn.yml

This closes #464
Properly this time with the new information. Thanks @stevenflang 
Replace the NET_ADMIN with privileged
https://github.com/binhex/arch-qbittorrentvpn/commit/391f1a23467203df0c041b60dafecb3bea995570
https://github.com/binhex/arch-delugevpn

Use privileged instead of NET_ADMIN on qBittorrentVPN

---

.scripts/update_self.sh

for older versions of git that do not support -C
This closes #477 
`cd` before `git` commands and stop using the `-C` flag.

Adjust git commands in update_self

---

compose/.apps/logarr/logarr.yml

Somehow we mapped `/app`, this is incorrect.
https://github.com/Monitorr/logarr/wiki/(03)-Docker
https://hub.docker.com/r/monitorr/logarr/dockerfile

Fix logarr config

---

.scripts/menu_value_prompt.sh

This closes #379 
Take the guesswork out of setting LAN_NETWORK
System detect the LAN_NETWORK value for the menu. Replace "Use System" with "Use Home" for all MEDIADIR prompts. Add a message whenever a system detected option is present to indicate that the system detected value is recommended.
https://github.com/tom472/mediabox/commit/d6a3317c9513ac9907715c76fb4459cba426da18
https://stackoverflow.com/questions/13322485/how-to-get-the-primary-ip-address-of-the-local-machine-on-linux-and-os-x#comment89955893_25851186

Lan network

---

.scripts/install_compose.sh

Fix compose install failure due to pip issues.
The pip dependencies will try to install but are ok to fail because compose itself will also try to install its own dependencies. DS installing pip dependencies is more of a helping hand than a requirement.

Adjust pip failures

---

compose/.apps/openvpnas/openvpnas.ports.yml
compose/.apps/pihole/pihole.ports.yml
compose/.apps/plex/plex.ports.yml
compose/.apps/telegraf/telegraf.ports.yml

Specifying `/tcp` is not necessary for port definitions.
Stop specifying `/tcp`
https://docs.docker.com/compose/compose-file/#ports

Remove unneeded tpc port specification`

---

.scripts/cmdline.sh
.scripts/update_self.sh

Define the default branch to be used when no branch is set from inside the `update_self` function. Other places in the code were calling this function without providing the branch and this is a safer long term plan to prevent issues. Prior to this commit some attempts to update would run with no branch specified.

Adjust default branch handling

---

.scripts/menu_value_prompt.sh

df77fc8148e235a0cf272315a84334b77d40013c adjusted prompts to `Use Home` for certain items but did not properly handle when a user selected that option.
Add handling of `Use Home` option.

Properly handle user selecting Use Home

---

compose/.apps/hydra2/hydra2.aarch64.yml
compose/.apps/hydra2/hydra2.armv7l.yml
compose/.apps/jackett/jackett.aarch64.yml
compose/.apps/jackett/jackett.armv7l.yml
compose/.apps/syncthing/syncthing.aarch64.yml
compose/.apps/syncthing/syncthing.armv7l.yml

Update a handful of ARM images to LSIO's new builds.
https://hub.docker.com/r/linuxserver/hydra2/
https://hub.docker.com/r/linuxserver/jackett/
https://hub.docker.com/r/linuxserver/syncthing/

Update Hydra2, Jackett, and Syncthing to LSIO pipeline images

---

compose/.apps/qbittorrent/qbittorrent.aarch64.yml
compose/.apps/qbittorrent/qbittorrent.armv7l.yml

https://hub.docker.com/r/linuxserver/qbittorrent

Switch qbittorrent to LSIO pipeline

---

compose/.apps/openvpnas/openvpnas.yml

Privileged mode seems to no longer be required and has been replaced with net_admin in the official documentation. The other changes in the PR linked below were already addressed in DS.
https://github.com/linuxserver/docker-openvpnas/pull/49

Replace privileged with net_admin on openvpnas

---

.scripts/update_self.sh

If only the `master` branch exists during DS's update process an `fatal: branch name required` message is shown because there are no branch names being passed to the command that deletes the extra branches. The command does not fail because we already had an `|| true` in place, but the error was not silenced. The error is not an important one and is expected behavior but does not need to be shown to the end users.
Redirect output to null.

Silence branch cleanup

---

.scripts/env_update.sh
.scripts/run_compose.sh

This closes #563 
Only set permissions on `DOCKERCONFDIR` if it is outside of `SCRIPTPATH` (if it's inside then permissions will be set by the parent being set). Do not run the set permissions sequence when running compose as it would have already been done by now via other parts of the script and thus would be redundant at this point.

Reduce the number of times set_permissions is called

---

README.md

Piping curl to shell is not perfect by any stretch and is considered bad practice (see the links below). I have already done the research before ever adding this method to the readme and done everything possible to minimize the potential negatives of offering this method while still using it for the sake of having a very minimal set of install instructions. Two things that have been done (prior to this commit, just noting for documentation) are using DNSSEC on the domain which should negate most intercept attempts and using curl with silent failures into a variable meaning if the script is not downloaded in its entirety the variable will be blank and nothing will run. This does not negate the possibility that the script downloaded could potentially not be the intended script as there are …

Add advanced install instructions

---

.scripts/install_compose.sh
.scripts/install_docker.sh
.scripts/install_yq.sh
main.sh

This closes #575 
Add version comparing functions to the main script since there are multiple of them and using `run_script` doesn't make sense (would require multiple files). Only perform installs/upgrades if the available version is greater than the installed version (or forced install/upgrade)
https://stackoverflow.com/questions/4023830/how-to-compare-two-strings-in-dot-separated-version-format-in-bash#comment92693604_4024263

Use better version checking

---

.scripts/cmdline.sh
.scripts/config_global.sh
.scripts/config_vpn.sh
.scripts/menu_app_select.sh
.scripts/menu_app_vars.sh
.scripts/menu_backup.sh
.scripts/menu_config.sh
.scripts/menu_main.sh
.scripts/menu_value_prompt.sh
.scripts/prune_docker.sh
.scripts/question_prompt.sh
.scripts/request_reboot.sh
.scripts/run_compose.sh
.scripts/run_install.sh
.scripts/update_self.sh
.tests/run_generate_slim.sh
main.sh

This closes #382 
Default to not prompt for most things
Use sane default for opting into prompts as needed
Remove the actual reboot code and instruct the user to manually reboot
Create a standard question prompt function since we're reusing that logic a lot. Allow the question prompt function to prompt as CLI or GUI (although we currently do not have any need for CLI prompts, keeping the option for the future). Get rid of the code that performs a reboot and replace it with information requesting that the user perform the reboot manually along with a warning stating the importance of a reboot on first run.
Edit: I've also added a significant rework of any place we used a `yesno` with `whiptail` so that it all uses the same standard code. There's also some minor renaming to ensure that …

Switch to universal prompt code

---

.scripts/cmdline.sh
.scripts/config_global.sh
.scripts/config_vpn.sh
.scripts/menu_app_vars.sh
.scripts/menu_config.sh
.scripts/menu_main.sh
.scripts/menu_value_prompt.sh
.scripts/prune_docker.sh
.scripts/question_prompt.sh
.scripts/run_compose.sh
.scripts/update_self.sh
main.sh

Follow up to #577 
I don't exactly know why I added these back in other than it seemed easy and useful, but they serve no purpose and the `readonly PROMPT="GUI"` line in main.sh can be adjusted in the future if we ever need to make use of something like `readonly PROMPT="CLI"` which is accommodated for in `question_prompt`.

Remove use of PROMPT and INTERFACE variable wherever possible

---

.scripts/cmdline.sh

Just keeping with the conventions of the repo.
run_script is always followed by the name of the function in single quotes unless a variable is used in which case double quotes are used.

Use single quotes to match other conventions

---

main.sh

Prevent Travis from constantly redoing the symlink (and likely causing other odd behavior) by ensuring it's using the correct path.
Use the `TRAVIS_BUILD_DIR` variable defined by Travis. As of creating this PR the variable should contain `/home/travis/build/GhostWriters/DockSTARTer/`
https://docs.travis-ci.com/user/environment-variables

Resolve issues with Travis get_scriptname

---

main.sh

Follow up to #589 
Don't hard code `main.sh`
Use `basename` on `${SOURCE}` which contains `./main.sh`

Use basename with Travis get_scriptname

---

compose/.apps/netdata/netdata.aarch64.yml
compose/.apps/netdata/netdata.armv7l.yml

This closes #593 
Switch to new multiarch images provided by netdata.
https://hub.docker.com/r/netdata/netdata/

Use multiarch Netdata images for ARM CPUs

---

.scripts/update_self.sh

Fetch all remotes and prune unused/merged.

Use --all and --prune with git fetch

---

main.sh

Follow up to #600 #589 #590 
The Travis specific code is no longer needed.

Remove workaround in get_scriptname for Travis

---

.scripts/backup_create.sh
.scripts/generate_yml.sh
.scripts/install_docker.sh

Stop piping to shell with docker install. Use mktemp for yml generator instead of fixed file location inside the repo. Minor tweaks for use of mktemp in other places.
Setup mktemp files into variables wherever they are used (already being done for some things). Use the variable as the path to the file.

Utilize mktemp for docker install

---

.scripts/install_compose.sh
.scripts/install_docker.sh
.scripts/run_python.sh
.scripts/run_yum.sh

Adjust for different versions of python on different systems. #621 introduced issues with CentOS which does not symlink `python3`.
Support all versions of python3 that are not EOL explicitly with their version number (ex: `python3.7`) as well as allowing `python3` itself to be valid as a fallback if it exists regardless of the version it may link to.
https://devguide.python.org/#status-of-python-branches

Run python

---

compose/.apps/airdcpp/airdcpp.yml
compose/.apps/delugevpn/delugevpn.yml
compose/.apps/emby/emby.yml
compose/.apps/nzbgetvpn/nzbgetvpn.yml
compose/.apps/pyload/pyload.yml
compose/.apps/qbittorrentvpn/qbittorrentvpn.yml
compose/.apps/rtorrentvpn/rtorrentvpn.yml
compose/.apps/sabnzbdvpn/sabnzbdvpn.yml
compose/.apps/samba/samba.yml

Some containers were missing common directories such as `/shared` while others had non standard mapping for things like `/movies`.
Keep existing mappings but add the standard mappings in addition wherever a non standard mapping is used. Add all missing common directories.

Add standard/common directories where missing

---

compose/.apps/grafana/grafana.yml

Include the PGID with Grafana. This is more so that I don't lose track of how this works after looking up the proper syntax. I have previously mistakenly suggested someone use `group: ${PGID}` which was incorrect.
`user: ${PUID}:${PGID}`
https://docs.docker.com/engine/reference/run/#user
https://docs.docker.com/compose/compose-file/#domainname-hostname-ipc-mac_address-privileged-read_only-shm_size-stdin_open-tty-user-working_dir

Add PGID to Grafana

---

main.sh

Fixes #649 and fixing terminal check not handled properly, see https://github.com/GhostWriters/DockSTARTer/issues/649#issuecomment-484918965
Use of `tput` to handle the color escape-sequences automatically for a large numbers of terminals.
Terminals in this context is not the program you use to run bash rather the terminal your program emulates.
Task no.1 can be tested by running the script normally and by setting `TERM` to different values.
```console
$ export TERM="screen"
$ sudo ds
```
will emulate screen for example. 
Testing that root check triggers can be done by this **dangerous** command
```console
$ sudo su root -l; ds; exit
```
**N.B. Changing user to root is very dangerous as you will have access to anything on your system and if you are not cautious with what you are doing you …

Use terminal capability instead of ANSI color codes

---

.scripts/backup_create.sh
.scripts/backup_max.sh
.scripts/backup_med.sh
.scripts/config_apps.sh
.scripts/config_global.sh
.scripts/config_vpn.sh
.scripts/env_get.sh
.scripts/env_set.sh
.scripts/env_update.sh
.scripts/generate_yml.sh
.scripts/install_compose.sh
.scripts/install_docker.sh
.scripts/install_yq.sh
.scripts/menu_app_select.sh
.scripts/menu_app_vars.sh
.scripts/menu_backup.sh
.scripts/menu_config.sh
.scripts/menu_main.sh
.scripts/menu_value_prompt.sh
.scripts/question_prompt.sh
.scripts/run_compose.sh
.scripts/set_permissions.sh
.scripts/update_self.sh
main.sh

This closes #650 
I had previously made efforts to always declare and set separately because I misunderstood the rule SC2155.
Set the value of local variables when declaring them local unless the value is being set via a command which is prohibited by shellcheck.
Also add the `local` declaration to a few places that were previously missed and we're accidentally setting at a global scope.
Also adjust the backup script to properly declare locals inside loops based on the scope actually needed (I thought I had it right, but this worked out to be a good time to review it).
[SC2155](https://github.com/koalaman/shellcheck/wiki/SC2155)

Declare locals inline

---

.scripts/set_permissions.sh

This closes #658 
Not a lot to say here other than what's already in the issue (which is very minimal). The main purpose of this is to keep DS from setting ownership to root when run via cron. Generally speaking there is no reason for root to be given ownership of anything by DS.

Don't set permissions as root

---

.scripts/menu_value_prompt.sh
compose/.env.example

`appdata` is a fairly consistent term among the community to refer to where apps store their data. I believe this originated with UnRaid, but since it's common enough even outside of UnRaid users I believe it is a good move to make this the default for DS. Existing users will be unaffected.
Change all references from `~/.config/docker` and `~/.docker/config` to `~/.config/appdata`. Our `env_sanitize` will still replace `~` with the absolute path of the home folder for the user and this will remain consistent with expected behaviour in the rest of DS.

Use appdata naming for default config locations

---

.github/opencollective.yml

Add the config file for the OpenCollective bot which will add comments to issues opened on the repo. If this becomes intrusive we will remove it.
Add the config file per the documentation. We will allow the bot to use it's default settings for now and if needed we can adjust them more specifically in the future.
https://github.com/opencollective/opencollective-bot

Add OpenCollective bot config

---

docs/advanced/smb-mounting.md

Updating the wording of smb-mounting.md documentation as it was telling users to create one file and it was instructing them to call for another file
This tutorial was telling users to create a file called `.credentials` but on line 18 it was having them use `.mount-creds` instead of `.credentials` which would result in a "file not found error". 
Proposed change will avoid future confusion.
_Describe the research stage_
_Links to blog posts, patterns, libraries or addons used to solve this problem_

Correcting wording smb-mounting.md

---

README.md

The Backer and Sponsor badges were linking to the images rather than the OC lins.
https://opencollective.com/DockSTARTer#backer
https://opencollective.com/DockSTARTer#sponsor

Make the shield badges links

---

README.md

This PR update the Readme to track 'backer' and 'sponsor' tiers on Open Collective, instead of relying on the confusing default behavior for GitHub readmes.
Current version: https://github.com/GhostWriters/DockSTARTer/blob/master/README.md
New version: https://github.com/znarf/DockSTARTer/blob/patch-1/README.md

Update opencollective backers / sponsors

---

compose/.apps/jellyfin/jellyfin.aarch64.yml
compose/.apps/jellyfin/jellyfin.armv7l.yml
compose/.apps/jellyfin/jellyfin.ports.yml
compose/.apps/jellyfin/jellyfin.x86_64.yml
compose/.apps/jellyfin/jellyfin.yml

Use LSIO's new jellyfin image.
Adjust variables and add new port.
https://hub.docker.com/r/linuxserver/jellyfin

Switch to LSIO jellyfin

---

README.md

Remove outdated information about Ubuntu 18.10. Include information linking to which systems and versions are supported. Note that as of writing 18.10 is supported and 19.04 is waiting for a release in https://download.docker.com/linux/ubuntu/dists/disco/pool/stable/amd64/
https://docs.docker.com/install/#supported-platforms
https://docs.docker.com/install/linux/docker-ce/debian/#os-requirements
https://docs.docker.com/install/linux/docker-ce/ubuntu/#os-requirements
https://docs.docker.com/install/linux/docker-ce/fedora/#os-requirements
https://docs.docker.com/install/linux/docker-ce/centos/#os-requirements

Add System Requirements info

---

compose/.apps/emby/emby.labels.yml

Fix missing `EMBY_TRANSCODEDIR`
Add the label so that emby will create the correct variable.

Add EMBY_TRANSCODEDIR

---

.scripts/appvars_create.sh
.scripts/appvars_create_all.sh
.scripts/appvars_purge.sh
.scripts/appvars_purge_all.sh
.scripts/cmdline.sh
.scripts/config_apps.sh
.scripts/generate_yml.sh
.scripts/menu_app_vars.sh
.scripts/update_self.sh

Ensure all appvars are created before they are needed. Ex: before prompting the user to edit them, or before trying to run containers that would use them.
Scenario: User who has `plexinc/pms-docker` prior to DS switching to `linuxserver/plex` would have incorrect variables after upgrading DS and not get the new variables automatically.
Create `appvars_create_all` and run it in specific places. Also run `appvars_create` for specific apps when prompting for that app's vars. Also set app's enabled variable to true when adding its vars.

Create all appvars

---

.scripts/install_docker.sh
.scripts/remove_snap_docker.sh

This closes #748 
Move snap docker removal code to a separate script. Use `snap services docker` to confirm snap docker is installed (and not run the removal unnecessarily). Move the call in the script above where it detects it docker is installed.

Adjust snap docker removal

---

.scripts/detect_lan_network.sh
.scripts/env_sanitize.sh
.scripts/menu_value_prompt.sh

Adjust tilde sanitizer so that it only looks for variables that end in DIR. This way if `=~` were used somewhere in the value of another variable (for example a complex password) it is not replaced.
Move LAN_NETWORK detection to a separate script so that it can be reused in multiple places.
Set LAN_NETWORK for the user if it contains an x …
x will be present in the default value, and is not valid in a CIDR
Many users asking for support overlook this
This should also prevent overwriting values that users have manually set themselves (if they set them correctly and did not include an x)
- - [x] Confirm LAN_NETWORK menu still works
- - [x] Confirm tilde directories are still replaced
- - [x] Confirm LAN_NETWORK is correctly set whenever it contains an `x` (the default value from .env.example …

Sanitizer improvements

---

compose/.apps/portaineragent/portaineragent.hostname.yml
compose/.apps/portaineragent/portaineragent.yml

Setting the hostname to match the docker host breaks this container. Also there are some additional capabilities added using an extra volume and environment variable.
Comment out the hostname directive, but keep it so we have a reminder of why it was commented out.
https://portainer.readthedocs.io/en/stable/agent.html

Fix portaineragent

---

.scripts/cmdline.sh
.scripts/docker_compose.sh
.scripts/docker_prune.sh
.scripts/menu_config.sh
.scripts/menu_main.sh
.scripts/pm_apt_install.sh
.scripts/yml_merge.sh

Rename functions to more closely match the name of the primary command the function performs.
`.scripts/run_compose.sh` → `.scripts/docker_compose.sh`
Primary commands are `docker-compose ...`
`.scripts/prune_docker.sh` → `.scripts/docker_prune.sh`
Primary command is `docker system prune`
`.scripts/generate_yml.sh` → `.scripts/yml_merge.sh`
Primary command is `yq-go m` (merge)
Testing has also been updated to resolve build errors.

Rename some functions

---

.scripts/set_permissions.sh

This is causing issues with Travis builds. It was added because Travis was unhappy without it, but it seems to pass builds workout it now.
Remove the code causing builds to fail
https://travis-ci.com/GhostWriters/DockSTARTer/builds/120521276

Adjust set_permissions for travis

---

compose/.apps/codeserver/codeserver.hostname.yml
compose/.apps/codeserver/codeserver.labels.yml
compose/.apps/codeserver/codeserver.netmode.yml
compose/.apps/codeserver/codeserver.ports.yml
compose/.apps/codeserver/codeserver.x86_64.yml
compose/.apps/codeserver/codeserver.yml

Add Code-Server
Removed the `-` in the name so it can be used in DS.
https://hub.docker.com/r/linuxserver/code-server

Add codeserver

---

.scripts/menu_value_prompt.sh
compose/.env.example

Show the `VALUEDESCRIPTION` on the `Enter New`  screen. Also default `VPN_PROV` to `custom` because that's technically universal and will work with any provider as long as you put your ovpn file in place.

Menu tweak

---

compose/.apps/samba/samba.labels.yml
compose/.apps/samba/samba.yml

Follow up to #772 
Specify the samba share name via `.env` rather than using the hostname variable.
Disable guest access (users can specify additional shares and configure them however they like, such as including guest access).
https://github.com/dperson/samba

Samba Adjustments

---

compose/.apps/transmissionvpn/transmissionvpn.yml

This closes #771
TransmissionVPN stores state information and other important things in `TRANSMISSION_HOME` so we are now persisting that as a volume. I have also added a second location for `VPN_OVPNDIR` so that *.ovpn files can reference this location for credential files.
This is unfortunately not documented as of writing, however the code can be seen in commits and in the repo https://github.com/haugene/docker-transmission-openvpn/search?q=TRANSMISSION_HOME

Transmissionvpn

---

main.sh

Some people have reported first install gets stuck due to prompts requiring user interaction that are hidden by DS. Using verbose mode these should not be hidden.
Add the verbose flag to the first install flag.

First install with verbose

---

.scripts/pm_apt_remove_docker.sh
.scripts/pm_dnf_remove_docker.sh
.scripts/pm_yum_remove_docker.sh

The ubuntu/debian pages contained two new packages that should be removed, `containerd` and `runc`. The centos page did not contain some packages that we were attempting to remove, which was likely because originally the yum and dnf scripts were copied from each other. Aside from that I have sorted the packages alphabetically just for cleanliness.
NOTE: The `docker-compose` package is not mentioned to be removed in any of the documentation (links below) but I have found at least on ubuntu that this is necessary if compose was installed via apt. I've included it in all the pm remove scripts just in case.
https://docs.docker.com/install/linux/docker-ce/centos/#uninstall-old-versions
https://docs.docker.com/install/linux/docker-ce/debian/#uninstall-old-versions …

Update removal of conflicting docker packages

---

compose/.apps/transmission/transmission.ports.yml

Transmission also uses UDP.
This change exposes ${TRANSMISSION_PORT_51413} as UDP

Expose UDP as well

---

compose/.apps/samba/samba.labels.yml
compose/.apps/samba/samba.ports.yml

Samba is not making the shares discoverable. This fixes the issue.
Adjust the ports used add correctly use UDP on the ports that need it.

Fix samba ports for network discovery

---

README.md

Raspbian needs extra install steps. Also sync some changes from .com repo.

Add separate Raspbian instructions

---

main.sh

This closes #796 
Run update and then install if DS repo is detected but the script running is not in the repo location. This is aimed at users who run the bash curl install command after already having DS installed. A common reason for this is if the install fails on the first attempt and the user reruns the command.

Run update and install from curl

---

.scripts/update_self.sh

CI has trouble with the git commands
Skip the git reset in CI.

Don't git reset in CI

---

.scripts/pm_yum_install.sh
.scripts/pm_yum_remove_python.sh

Package python36u-pip is obsoleted by python3-pip

Replace python36u with python3 for CentOS

---

.scripts/install_compose.sh
.scripts/pm_apt_remove_python_conflicts.sh
.scripts/pm_dnf_remove_python_conflicts.sh
.scripts/pm_yum_remove_python_conflicts.sh

**Purpose**
Adjust script naming to be clear that we're not removing python, rather only removing conflicting packages from python.

Adjust python conflict script naming

---

.scripts/install_compose.sh
.scripts/install_docker.sh
.scripts/install_yq.sh

**Purpose**
Ensure that we get the minimum required version of dependencies installed. The need for this was discovered while testing setting the minimum version for yq to 3 which at the time of testing and writing this is unreleased. The rest of the script thought the minimum version had been installed because the version that was installed was not less than the latest available version.
We should never set the minimum version higher than the latest available version, but the logic should be in place to catch this scenario.
**Approach**
Add a check against the minimum version and the updated version (the version just installed).

Check minimum required deps

---

compose/.apps/cloudflareddns/cloudflareddns.labels.yml
compose/.apps/cloudflareddns/cloudflareddns.yml

**Purpose**
Cloudflare has added API Tokens for more granular control of access to your account. The API Key can still be used but API Tokens are a more secure approach.
**Approach**
Adding the supported variable, CF_APITOKEN, to the yml makes this possible.
**Learning**
After trying to use an API Token for the API Key, the container provided an error that the configuration was invalid. Looking at the documentation at https://hub.docker.com/r/hotio/cloudflare-ddns/ the container supports the use of API Tokens in lieu of using an API Key (CF_APIKEY) with CF_USER

Add API Token option to CloudflareDDNS

---

main.sh

**Purpose**
Always output to file even if not outputting to the console.
**Approach**
Create a `log` function that handles output from other log functions. The new `log` function is passed two parameters; one to determine if output should go to the console, and the other containing what is being logged (the message). Logging always goes to the log file, but only goes to the console when the first parameter is a truthy value. We are continuing to use `tee -a` when logging to the console and log file. We are using `cat >>` when only logging to the log file.
No changes to the use of existing log functions is required.

Change log behavior

---

compose/.apps/letsencrypt/letsencrypt.labels.yml

**Purpose**
Better description for the letsencrypt container.
**Learning**
https://github.com/linuxserver/docker-letsencrypt

Fix letsencrypt description

---

compose/.apps/netdata/netdata.yml

**Purpose**
Resolve issues reported on Discord.
**Approach**
Remove the config volume (users can still add it via override). This causes issues because the container expects certain files to be in that folder. The files are included inside the container and not copied to user mounted volumes.
Added a few more volumes per the documentation.
**Learning**
https://docs.netdata.cloud/packaging/docker/

Update netdata volumes

---

.scripts/env_sanitize.sh

**Purpose**
Remove the code (that was meant to be temporary anyway) that relocates ovpn files from individual app config folders into a global folder. We've had a long enough transition period, and have had a number of issues raised (Reddit and discord) about slowness caused by this code.

Remove ovpn relocation

---

.gitignore
main.sh

**Purpose**
Instructing a user to locate their log file will be increasingly difficult since https://github.com/GhostWriters/DockSTARTer/pull/914 which was primarily introduced to resolve permission issues with Ubuntu 20.04 and things previously seen on CentOS and Fedora. This will consolidate the logging back into a location that is easily found by the user.
There is the potential that this could cause other permissions related issues for users, but since it fires as one of the very last things the script does, and we are using `|| true` to force the exit code it should be fine hopefully. 
**Approach**
Continue printing logs to the temp location but bring them into a central location when the script terminates. …

Append temp logs on cleanup

---

compose/.apps/qbittorrentvpn/qbittorrentvpn.yml

**Purpose**
Privileged mode should be avoided. qbit required it in the past but users have reported to binhex that it is no longer required.
**Approach**
Swap privileged mode for net admin.
**Learning**
https://github.com/binhex/arch-qbittorrentvpn/issues/1

Use NET_ADMIN instead of privileged mode

---

.scripts/install_compose.sh
.scripts/install_docker.sh
.scripts/install_yq.sh

**Purpose**
Don't fatal when latest dependency install fails. There's a fatal right after that logic to endure the minimum version is installed. Instead show an error letting the user know the latest was not installed.
Remove compose image when installing compose to ensure a new image is pulled.

Install deps

---

.scripts/appvars_purge.sh
.scripts/appvars_purge_all.sh
.scripts/install_compose.sh
.scripts/install_docker.sh
.scripts/install_yq.sh
.scripts/pm_apt_upgrade.sh
.scripts/pm_dnf_upgrade.sh
.scripts/pm_yum_repos.sh
.scripts/pm_yum_upgrade.sh
.scripts/question_prompt.sh
main.sh

**Purpose**
Don't show users a prompt when they run most CLI flags. Some will still require a prompt because we would not want to purge user data without a confirmation.
Slipped in only forcing install for compose/docker/yq when running the install flag (with the force flag). Also corrected some syntax `[[ cond1 && cond2 ]]` => `[[ cond1 ]] && [[ cond2 ]]`.
**Learning**
Following up from #780 which unintentionally had the side effect of bringing prompts back for everything.
Prompts were debated on discord and voted to be removed for CLI. This was completed in https://github.com/GhostWriters/DockSTARTer/pull/577 and adjusted a bit in https://github.com/GhostWriters/DockSTARTer/pull/585
Check all …

Reduce prompts

---

main.sh

**Purpose**
The workaround is pointless. `export` should resolve the issue to pass shellcheck.
I am considering exporting all variables, or all readonly variables, or only exporting variables that cause shellcheck to throw a fit. I'm undecided at the moment.

Export instead of workaround

---

docs/overrides/yacreader.md
mkdocs.yml

**Purpose**
Created a Override page for YACReader-Server
YACReader is for Reading, Browsing, And Managing your Digital Comics Collection.
**Learning**
Website is [YacReader.com](https://yacreader.com)
The GIT Repository for YACReader Server is located at 
[https://github.com/josetesan/yacreaderlibrary-server-docker](https://github.com/josetesan/yacreaderlibrary-server-docker)
The Docker Hub link for YACReader Server is
[https://hub.docker.com/r/muallin/yacreaderlibrary-server-docker](https://hub.docker.com/r/muallin/yacreaderlibrary-server-docker)
- [Y] These changes meet the standards for [contributing](https://github.com/GhostWriters/DockSTARTer/blob/master/.github/CONTRIBUTING.md).
- [Y] I have read the [code of …

Create overrides page for YACReader Server

---

compose/.apps/traktarr/traktarr.armv7l.yml

**Purpose**
Traktarr would not install on ARM - giving the following error:
> [ERROR ]   Failed to include /home/user/.docker/compose/.apps/traktarr/traktarr.armv7l.yml file.
**Approach**
Adds the required yml file for ARM
**Learning**

Add ARM support for Traktarr

---

.github/workflows/label.yml

**Purpose**
Labeling fails when PRs are made from forks. Add logic to only run on self (not forks).

Only label on self (not forks)

---

compose/.apps/portainer/portainer.labels.yml
docs/advanced/advanced-usage.md
docs/basics/faq.md

**Purpose**
Do not enable portainer by default. It's a good tool, but with DS it's propose is more to see what's happening and not to take actions. Enabling it by default implies it is intended to be used.
**Approach**
Disable portainer by default. Update docs.

Portainer default

---

.github/workflows/CI.yml

**Purpose**
Ensure that DockSTARTer works on Ubuntu 20.04
**Approach**
Add additional OS to the list in the CI file

Also run CI on Ubuntu 20.04

---

compose/.apps/murmur/murmur.hostname.yml
compose/.apps/murmur/murmur.labels.yml
compose/.apps/murmur/murmur.netmode.yml
compose/.apps/murmur/murmur.ports.yml
compose/.apps/murmur/murmur.x86_64.yml
compose/.apps/murmur/murmur.yml
docs/apps/murmur.md
mkdocs.yml

**Purpose**
Murmur is the server for the Mumble voice-over-ip client.
**Approach**
This adds Murmur, a new application 

Add Murmur VoIP server

---

compose/.apps/speedtest/speedtest.yml

This is a bug fix. The container expects the variable to be OOKLA_EULA_GDPR. The service does not start as-is.
From the container logs: 
```
[cont-init.d] 50-speedtest: executing... 
##################################################################################################################################
##################################################################################################################################
You haven't accepted the Ookla EULA. Please re-create the container with the environment variable 'OOKLA_EULA_GDPR' set to 'true'.
##################################################################################################################################
############################################################################################# …
```

Correct variable name for speedtest service

---

README.md
docs/basics/support.md
docs/discord.md
mkdocs.yml

**Purpose**
Remade the invite link on discord to point to the rules channel (first channel users will see when joining). Setup a vanity url (redirect) for the invite (this makes it easier to update only one place in the future if we need to remake the invite again). Update all references to the invite link to the new vanity url.

Add discord invite redirect

---

.scripts/install_compose.sh
.scripts/install_yq.sh
.scripts/symlink_ds.sh
.scripts/yml_get.sh
.scripts/yml_merge.sh

**Purpose**
Don't call binaries using full paths, use what is in `$PATH` for better compatibility.
`rm` binaries where DS requires symlinks when installing compose and yq.
This begins working towards compatibility with more distros such as Arch.

Better handling of binaries in PATH

---

.scripts/package_manager_run.sh
.scripts/pm_pacman_clean.sh
.scripts/pm_pacman_install.sh
.scripts/pm_pacman_remove_docker.sh
.scripts/pm_pacman_repos.sh
.scripts/pm_pacman_upgrade.sh
README.md

We currently don't detect pacman, and it looks like there is no package manager. Instead of exiting, tell the user they need to install docker and docker-compose (both from Arch repos, easy to do) and let the script work normally. This allows DockSTARTer to work on Arch despite not officially supporting it in the same manner as other distributions.

Add Arch Linux Support

---

.scripts/update_self.sh

**Purpose**
The `.git` folder is often left owned by root. This corrects permissions on the folder. Likely only noticed by developers/contributors. End users would only see an effect (with root owning the folder) if they tried to run `git` commands in the repo folder.

Fix permissions on .git folder

---

.github/workflows/mkdocs.yml
docs/CNAME

**Purpose**
This is a more direct approach and will use direct versions from mkdocs-material rather than abstracting the version behind another GHA.
**Learning**
https://github.com/squidfunk/mkdocs-material/blob/master/docs/publishing-your-site.md

Use mkdocs-material from pip

---

compose/.apps/calibre/calibre.aarch64.yml
compose/.apps/calibre/calibre.armv7l.yml

**Purpose**
Removes arm64 and armhf YML files from Calibre
Per LSIO:
```
Architecture | Tag
-- | --
x86-64 | latest
```
**Approach**
**Learning**

Removing Calibre non-x86_64 YML

---

compose/.apps/quasselweb/quasselweb.aarch64.yml
compose/.apps/quasselweb/quasselweb.armv7l.yml
compose/.apps/quasselweb/quasselweb.x86_64.yml

This reverts commit 4b6925980342508fc62b41f2431a559959fe8ebf.
https://github.com/linuxserver/docker-quassel-web
Wait for the image to be available on GHCR.

Revert "Use DH for quasselweb"

---

compose/.apps/unificontroller/unificontroller.aarch64.yml
compose/.apps/unificontroller/unificontroller.armv7l.yml
compose/.apps/unificontroller/unificontroller.x86_64.yml

This reverts commit f7c815d3629201a90ad230cdfcc2f824fc59e373.
https://github.com/linuxserver/docker-unifi-controller
Wait for the image to be available on GHCR.

Revert "Use DH for unificontroller"

---

compose/.apps/beets/beets.aarch64.yml
compose/.apps/beets/beets.armv7l.yml
compose/.apps/beets/beets.x86_64.yml

This reverts commit e5345e510d12a6175edc9e8038becfacb038ab13.
https://github.com/linuxserver/docker-beets
Wait for the image to be available on GHCR.

Revert "Use DH for beets"

---

compose/.apps/pyload/pyload.aarch64.yml
compose/.apps/pyload/pyload.armv7l.yml
compose/.apps/pyload/pyload.x86_64.yml

This reverts commit e36b7f77d5078577a5817e7a52e41f063221bb99.
https://github.com/linuxserver/docker-pyload
Wait for the image to be available on GHCR.

Revert "Use DH for pyload"

---

compose/.apps/filebrowser/filebrowser.labels.yml
compose/.apps/filebrowser/filebrowser.ports.yml
compose/.apps/filebrowser/filebrowser.yml

**Purpose**
Fixes https://github.com/GhostWriters/DockSTARTer/issues/1175
**Approach**
The port documented is 80, however we went with 8080 by default originally due to host user permissions. This keeps the default port 8080 but applies it in a way that the app and container should both recognize.

Fix filebrowser port inconsistencies

---

main.sh

**Purpose**
A new release of ShellCheck seems to not like the way we had `readonly` declared for some variables. This resolves the issue by abiding by the new recommendations.
**Learning**
https://github.com/koalaman/shellcheck/wiki/SC2155#problematic-code-in-the-case-of-readonly

Fix new SC2155 readonly issues

---

.scripts/install_yq.sh

**Purpose**
4.x has breaking changes we will need to adjust for
**Approach**
Hardcode the `AVAILABLE_YQ` so that DS does not install anything newer than the defined version.

Pin yq-go version to 3.4.1

---

.scripts/yml_merge.sh

**Purpose**
`yq` might not be aware of the `SCRIPTPATH` when running inside docker.
**Approach**
Set `YQ_OPTIONS` to include `SCRIPTPATH` as a volume when running `yq` via `yml_merge` so that we are positive that the yml templates will be available.
**Learning**
https://github.com/linuxserver/docker-yq/blob/master/run-yq.sh

Include SCRIPTPATH in YQ_OPTIONS when running yq

---

compose/.apps/smokeping/smokeping.yml

**Purpose**
Smokeping apparently has an issue working without DNS entries in compose?
**Approach**
Add DNS entries to compose.
**Learning**
https://github.com/linuxserver/docker-smokeping/issues/86

Add DNS to smokeping

---

compose/.apps/cloudflareddns/cloudflareddns.yml

Using
```shell
docker ps -a --format '{{ .ID }}' | xargs -I {} docker inspect -f '{{ .Name }}{{ printf "\n" }}{{ range .Mounts }}{{ printf "\n\t" }}{{ .Type }} {{ if eq .Type "bind" }}{{ .Source }}{{ end }}{{ .Name }} => {{ .Destination }}{{ end }}{{ printf "\n" }}' {}
```
to find volumes not being created as bind. Each one may need to be handled differently.

Add missing volume for cloudflareddns

---

compose/.apps/filebrowser/filebrowser.yml

Overrides built in healthcheck to fix the port that's set
**Purpose**
Filebrowser added a healthcheck which is incompatible with changing the port it's running on in the container
**Approach**
Override the healthcheck that comes with the container
**Learning**

Add healthcheck

---

.scripts/docker_compose.sh
.scripts/run_compose.sh
.scripts/run_yq.sh
.scripts/yml_merge.sh

**Purpose**
Reduce code complexity and allow simpler repetitive use of compose and yq.
As a result this also rids `yml_merge` of creating a temporary bash file to merge `docker-compose.yml` and instead appends everything to a variable and passes it as an argument to the new `run_yq` script. This should be more reliable long term, but is a fairly major change and should be properly tested.

Use run_script for compose and yq

---

compose/.apps/filebrowser/filebrowser.aarch64.yml
compose/.apps/filebrowser/filebrowser.armv7l.yml

**Purpose**
filebrowser docker supports arm and arm64, e.g. for running it with DockSTARTer on a Raspberry Pi
**Approach**
Adding relevant architecture-specific files

Add other supported filebrowser architectures

---

compose/.apps/glances/glances.armv7l.yml

**Purpose**
Want to install glances app on raspberry pi based on armv7 architecture.
**Approach**
Added in required docker-compose partial file to indicate to ds that glances is installable on armv7 architecture.
None afaik.
**Learning**
Checking the docker image repo, it has images for the armv7 architecture.
https://hub.docker.com/r/nicolargo/glances/tags

feat: add armvl7 arch for glances

---

README.md

**Purpose**
It's typical for the README on Github to directly have a link to CONTRIBUTING.md. As a new contributor myself I had trouble finding this and so I thought it makes sense to follow this pattern of directly linking to CONTRIBUTING from the README. 
**Testing**
Rendered README on https://markdownlivepreview.com/ and reviewed there
None
**Learning**
I pulled a lot of this text directly from [Docker Compose](https://github.com/docker/compose#contributing)

Adding contributing.md link to readme

---

main.sh

**Purpose**
SC2317 triggers when a script has code that is unreachable due to an `exit` happening before the code in question. These changes remove duplicate `exit` commands and reorder the `trap` to the top of the `cleanup`.
**Learning**
https://www.shellcheck.net/wiki/SC2317

Fix SC2317

---

compose/.apps/traefik/traefik.aarch64.yml
compose/.apps/traefik/traefik.hostname.yml
compose/.apps/traefik/traefik.labels.yml
compose/.apps/traefik/traefik.netmode.yml
compose/.apps/traefik/traefik.ports.yml
compose/.apps/traefik/traefik.x86_64.yml
compose/.apps/traefik/traefik.yml
docs/apps/traefik.md
mkdocs.yml

**Purpose**
Adding support for [Traefik](https://hub.docker.com/_/traefik)
**Approach**
Followed contributing.md for adding new app
**Testing**
1. ds -a traefik
2. Created traefik.yml with basic contents
```
providers:
docker:
defaultRule: "Host(`{{ trimPrefix `/` .Name }}.docker.localhost`)"
api:
insecure: true
```
3. Visited <host>:8080 and to ensure I can see the Traefik dashboard

Add Traefik App

---

compose/.apps/uptimekuma/uptimekuma.labels.yml

**Purpose**
Fixes an issue where installing UptimeKuma doesn't work because the nicename has a space in it:
```
$ sudo ds
[sudo] password for ds:
2022-08-30 04:42:40 [NOTICE]   Preparing app menu. Please be patient, this can take a while.
grep: /home/ds/.docker/compose/.apps/uptime kuma/uptime kuma.labels.yml: No such file or directory
2022-08-30 04:43:42 [ERROR ]   Unable to find labels for UPTIME KUMA
2022-08-30 04:43:42 [FATAL ]   Failed to find UPTIME KUMA_ENABLED in /home/ds/.docker/compose/.env
Failing command: grep --color=never -P "^UPTIME KUMA_ENABLED=" "/home/ds/.docker/compose/.env"
DockSTARTer did not finish running successfully.
```
**Approach**
Removing the space fixes this as the variables in the `.env` file become `UPTIMEKUMA_*`
Check …

Fix "Unable to find labels for UPTIME KUMA" error on creating Uptime Kuma

---

compose/.apps/gluetun/gluetun.labels.yml

**Purpose**
In [this pull request](https://github.com/GhostWriters/DockSTARTer/pull/1545) I left in a label for port 9117. This isn't required or used for Gluetun it's actually the port for Jackett that I must've left over from testing. I don't mean to spam this repository so sorry for that.

Removed unnecessary port label from Gluetun

---

compose/.apps/calibre/calibre.yml

**Purpose**
Calibre in DoskSTARTer is currently broken as referenced in #1540 and #1559 
**Approach**
This is the solution proposed by the linuxserver team. You will find it referenced at the following URL https://hub.docker.com/r/linuxserver/calibre
**Learning**
I applied the fix to my override file and it solved the issue with the failed startup.

Update Calibre to fix issue #1540

---

compose/.apps/prowlarr/prowlarr.aarch64.yml
compose/.apps/prowlarr/prowlarr.armv7l.yml
compose/.apps/prowlarr/prowlarr.x86_64.yml

**Purpose**
Prowlarr's `latest` tag via lsio image has been released. Switching from `develop` to `latest` to provide the most stable option by default.
**Learning**
https://github.com/linuxserver/docker-prowlarr

Switch prowlarr to latest

---

compose/.apps/audiobookshelf/audiobookshelf.hostname.yml
compose/.apps/audiobookshelf/audiobookshelf.labels.yml
compose/.apps/audiobookshelf/audiobookshelf.netmode.yml
compose/.apps/audiobookshelf/audiobookshelf.ports.yml
compose/.apps/audiobookshelf/audiobookshelf.x86_64.yml
compose/.apps/audiobookshelf/audiobookshelf.yml
docs/apps/audiobookshelf.md
mkdocs.yml

**Purpose**
Add audiobookshelf (audiobook and podcast server)
**Approach**
Audiobooksehlf has both a `config` and a `metadata` folder.  Since we only have a `config`, I placed the metadata folder in `/config/.metadata` using the `METADATA_PATH` variable.  He also no longer uses "UID/GID" variables, but using `user: ${PUID}:${PGID}` has been working for me instead to get the permissions right.
**Learning**

Add audiobookshelf

---

compose/.apps/audiobookshelf/audiobookshelf.labels.yml
compose/.apps/audiobookshelf/audiobookshelf.yml

**Purpose**
Mount the metadata folder into from `/metadata` to `/config/.metadata` instead of using `METADATA_PATH` variable.
**Approach**
**Learning**

audiobookshelf: remove METADATA var, mount into /config

---

compose/.apps/calibre/calibre.aarch64.yml

Lsio has added aarch64 architechure support to their calibre container sometime in the last two years. I added the aarch64.yml file needed for DS to pull that container.
**Purpose**
**Approach**
**Learning**
https://hub.docker.com/r/linuxserver/calibre

Calibre aarch64 support

---

compose/.apps/kiwixserve/kiwixserve.aarch64.yml
compose/.apps/kiwixserve/kiwixserve.armv7l.yml
compose/.apps/kiwixserve/kiwixserve.x86_64.yml

The default kiwix/kiwix-serve image location fails as it tries to pull from dockerhub rather than ghcr.io. This updates the files to pull from the correct location.
**Purpose**
The image location for kiwix/kiwix-serve is linking to dockerhub rather than ghcr.io where the images are actually located. This corrects that issue. As a result this also fixes the validation check that causes every PR to fail.
**Approach**
Changes the image location.
N/A
**Learning**
N/A

Update kiwix-serve image location

---

compose/.apps/apprise/apprise.labels.yml
compose/.apps/apprise/apprise.yml

**Purpose**
Seems to fix https://github.com/GhostWriters/DockSTARTer/issues/1679
**Approach**
**Learning**
I saw that [other containers had this tag](https://github.com/GhostWriters/DockSTARTer/blob/master/compose/.apps/amd/amd.labels.yml#L29C7-L29C48) but Apprise did not

Add apprise_tag to apprise.labels.yml

---

compose/.apps/postgres/postgres.aarch64.yml
compose/.apps/postgres/postgres.hostname.yml
compose/.apps/postgres/postgres.labels.yml
compose/.apps/postgres/postgres.netmode.yml
compose/.apps/postgres/postgres.ports.yml
compose/.apps/postgres/postgres.x86_64.yml
compose/.apps/postgres/postgres.yml
docs/apps/postgres.md
mkdocs.yml

**Purpose**
Added PostgreSQL app container
**Learning**

Add PostgreSQL container

---

compose/.apps/quasselweb/quasselweb.labels.yml

**Purpose**
LSIO quassel-web container checks that `QUASSEL_HTTPS` env
var has non-zero length, not explicit `true` or `false` values. The default
value of this env var was incorrectly set to `false` when adding support
for it to DockSTARTer.
**Approach**
Change the default value to an empty string.
**Learning**

Fix default value of quasselweb https

---

.scripts/package_manager_run.sh
.scripts/symlink_ds.sh

**Purpose**
Closes #1730. 
Tested on [ucore-hci from the Universal Blue project](https://github.com/ublue-os/ucore). Manual workaround needed for docker compose plugin:
```
DOCKER_CONFIG=${DOCKER_CONFIG:-$HOME/.docker}
mkdir -p $DOCKER_CONFIG/cli-plugins
curl -SL https://github.com/docker/compose/releases/download/v2.24.5/docker-compose-linux-x86_64 -o $DOCKER_CONFIG/cli-plugins/docker-compose
chmod +x $DOCKER_CONFIG/cli-plugins/docker-compose
```
I also set SELinux to permissive. After that, it worked perfectly and all my containers spun up. :-)
**Approach**
* Uses $HOME/bin instead of /usr for the filesystem
* Doesn't fail hard if it detects no supported package manager, instead checking if the commands we need are there.
**Open Questions and …

Make DockStarter work with CoreOS (immutable filesystem, no traditional package manager)

---

compose/.apps/prometheus/prometheus.yml

**Purpose**
Propose a fix for properly mounting volumes for data and config in the prometheus app ([issue 1777](https://github.com/GhostWriters/DockSTARTer/issues/1777))
**Approach**
Mount configuration to a prometheus folder in `DOCKERCONFDIR`. Data is mounted in a prometheus folder in `DOCKERSTORAGEDIR`.

Fix prometheus app data and config volumes

---

.scripts/menu_value_prompt.sh

`ds` was detecting variables such as `GLUETUN_ENVIRONMENT_VPN_PORT_FORWARDING` as being a `GLUETUN_PORT_XXXX` variable.
**Purpose**
**Approach**
**Learning**

fix: `ds` getting false positives for special variables

---

.scripts/menu_config.sh

**Purpose**
**Approach**
**Learning**

fix: Remove depreciated VPN variables settings option from config

---

.scripts/yml_merge.sh
compose/.reqs/r1.yml
compose/.reqs/r2.yml
compose/README.md

**Purpose**
Fix:
> WARN[0000] ~/.docker/compose/.reqs/r2.yml: the attribute version is obsolete, it will be ignored, please remove it to avoid potential confusion
**Approach**
Completely remove the two files in the `.reqs` folder and add an `if` statement to check if no apps were selected. The original intention with those files was just to hand something (anything) to `compose` (and in the past `jq`) so it is able to construct the `docker-compose.yml` file when a user does not have any apps selected to be enabled. Instead this just throws a `fatal`, which would also preserve any pre-existing `docker-compose.yml` file they may have had from a previous run (ex: maybe they just messed up their `.env`, which would probably mean they are not in a working state anyway, so exiting with `fatal` …

fix: :mute: remove reqs to fix version warning

---

compose/.apps/filebrowser/filebrowser.yml

**Purpose**
File browser healthchecks were always failing due to using the incorrect port.
This was caused by a change where the `FB_PORT` env variable is no longer set.
**Approach**
As the FB_PORT env variable is no longer set, internally, within the container, port 80 is now always used.
So, as health checks run inside the container, the internal port needs to be used and not the host port.

Fix filebrowser healthcheck

---

compose/.apps/logitechmediaserver/logitechmediaserver.labels.yml
compose/.apps/lyrionmusicserver/lyrionmusicserver.aarch64.yml
compose/.apps/lyrionmusicserver/lyrionmusicserver.hostname.yml
compose/.apps/lyrionmusicserver/lyrionmusicserver.labels.yml
compose/.apps/lyrionmusicserver/lyrionmusicserver.netmode.yml
compose/.apps/lyrionmusicserver/lyrionmusicserver.ports.yml
compose/.apps/lyrionmusicserver/lyrionmusicserver.x86_64.yml
compose/.apps/lyrionmusicserver/lyrionmusicserver.yml
docs/apps/lyrionmusicserver.md
mkdocs.yml

**Purpose**
Logitech Media Server has been discontinued and has been taken up by the community. They have renamed it as Lyrion Music Server. Dockstarter now has the wrong docker name and it is pulling form the wrong source. Issue: https://github.com/GhostWriters/DockSTARTer/issues/1830
**Approach**
This adds a new app called LyrionMusicServer, along with documentation. It leaves LogitechMediaServer in place, but changes the deprecated flag to "true" in logitechmediaserver.labels.yml
**Learning**
Logitech servers shut down about a year ago and the community released new docker images under the original name. Recently they have rebranded to Lyrion. This changed the name of the project, the website, and docker hub container. The github page is still the …

Add LyrionMusicServer/deprecate LogitechMediaServer

---

compose/.apps/pihole/pihole.labels.yml
compose/.apps/pihole/pihole.ports.yml
compose/.apps/pihole/pihole.yml

**Purpose**
PiHole released version 6 which had significant changes to the environment variables causing the existing DS compose to not work on the new version. 
**Approach**
CLHatch and I discussed this at length on Discord and they wanted DS to be backward compatible for users still on PiHole v5. This approach leaves in variables that are still in use by v5, but also adds new variables needed for v6. Each version uses the variables it needs, and ignores the other variables, allowing this compose to work for both versions.
- This has been tested by removing the `~/.config/appdata/pihole` directory every time to ensure a clean test. It was tested with 'host' mode, and default (bridge) mode. Tested on versions 5 …

PiHole additions for v6

---

compose/.apps/maintainerr/maintainerr.aarch64.yml
compose/.apps/maintainerr/maintainerr.hostname.yml
compose/.apps/maintainerr/maintainerr.labels.yml
compose/.apps/maintainerr/maintainerr.netmode.yml
compose/.apps/maintainerr/maintainerr.ports.yml
compose/.apps/maintainerr/maintainerr.x86_64.yml
compose/.apps/maintainerr/maintainerr.yml
docs/apps/maintainerr.md
mkdocs.yml

**Purpose**
This PR adds support for Maintainerr, a library management system that helps Plex administrators save storage by identifying and managing unwatched or unwanted media. Maintainerr creates collections based on user-defined rules and can automatically remove content after a set period, keeping media libraries optimized.
Closes #1823 
GitHub repository: https://github.com/jorenn92/Maintainerr
Documentation: https://docs.maintainerr.info/
**Approach**
I've implemented Maintainerr support in DockSTARTer by:
- Creating the necessary YML configuration files in `/compose/.apps/maintainerr/`
- Adding appropriate environment variables and default settings
- Creating documentation in /docs/apps/maintainerr.md
- Adding the navigation link in mkdocs.yml
The implementation follows the …

feat: 💥 Add Maintainerr

---

compose/.apps/tsdproxy/tsdproxy.aarch64.yml
compose/.apps/tsdproxy/tsdproxy.hostname.yml
compose/.apps/tsdproxy/tsdproxy.labels.yml
compose/.apps/tsdproxy/tsdproxy.netmode.yml
compose/.apps/tsdproxy/tsdproxy.ports.yml
compose/.apps/tsdproxy/tsdproxy.x86_64.yml
compose/.apps/tsdproxy/tsdproxy.yml
docs/apps/tsdproxy.md
mkdocs.yml

**Purpose**
This PR adds support for TSDProxy, an application that automatically creates a proxy to virtual addresses in your Tailscale network. Easy to configure and deploy, based on Docker container labels or a simple proxy list file. It simplifies traffic redirection to services running inside Docker containers, without the need for a separate Tailscale container for each service.
Closes #1855 
GitHub repository: https://github.com/almeidapaulopt/tsdproxy
Documentation: https://almeidapaulopt.github.io/tsdproxy
**Approach**
I've implemented TSDProxy support in DockSTARTer by:
- Creating the necessary YML configuration files in `/compose/.apps/tsdproxy/`
- Adding appropriate environment variables and default settings
- Creating documentation in /docs/apps/tsdproxy.md
- Adding the …

feat: 💥 Add TSDProxy

---

compose/.apps/autobrr/autobrr.yml

**Purpose**
This pull request includes a small fix in the `compose/.apps/autobrr/autobrr.yml` file. The change corrects the order of the `user` environment variable values, swapping `${PGID}:${PUID}` to `${PUID}:${PGID}` to align with the expected format.
**Learning**
The change aligns with Docker's standardised user format which follows the Linux convention of `user:group` (UID). As specified in Docker's official documentation for the --user flag (https://docs.docker.com/engine/reference/run/#user), the format should be `"user:group"` which translates to `${PUID}:${PGID}` in our environment variables.

🐛 fix(autobrr): correct PUID:PGID order in environment variable

---

main.sh

Fix the `ds -u` option that was broken when fixing `ds --update`
**Purpose**
**Approach**
**Learning**

Fix the `ds -u` option that was broken when fixing `ds --update`

---

.scripts/apply_theme.sh
.scripts/ds_update_available.sh
.scripts/ds_version.sh
.scripts/menu_add_app.sh
.scripts/menu_add_var.sh
.scripts/menu_app_select.sh
.scripts/menu_config.sh
.scripts/menu_config_apps.sh
.scripts/menu_config_vars.sh
.scripts/menu_dialog_example.sh
.scripts/menu_display_options.sh
.scripts/menu_display_options_general.sh
.scripts/menu_display_options_theme.sh
.scripts/menu_main.sh
.scripts/menu_value_prompt.sh
.scripts/question_prompt.sh
main.sh

**Purpose**
Adds an `(Update Available)` notice at the top of the usage page, and at the top right of dialog boxes.
Added the code to display version info as well, once versioning is implemented.  Currently, `ds_version` returns a blank string.
**Approach**
**Learning**

Add update notices, and initial version display

---

.scripts/app_instance_file.sh
.scripts/yml_merge.sh

Abort `yml_merge` on missing template files
Fix `app_instance_file` to always return a filename, even if the file doesn't exist.
**Purpose**
**Approach**
**Learning**

Abort `yml_merge` on missing template files

---

compose/.apps/handbrake/handbrake.devices.yml
compose/.apps/handbrake/handbreak.devices.yml

**Purpose**
**Approach**
**Learning**

Fix naming of `handbreak.devices.yml` to `handbrake.devices.yml`
